### ISSUE TITLE
Set up automated build system

### ISSUE THREAD

**Issue by TheWaveWarden** [TheWaveWarden/odin2#312]
'People over at Surge discord are very helpful:

- Jenkins?
- MS Azure?

**Comment by simonvanderveldt** [comment]
> * Jenkins?
> 
> * MS Azure?

Both options are pretty involved, no need to host/manage CI services yourself.
GitHub Actions would be a decent option, if for some reason you don't like that option I'd suggest CircleCI. It's quiet a lot faster than Travis (it's biggest competitor).

**Comment by TheWaveWarden** [comment]
Hi and thanks for your suggestions. I am setting up MS Azure as we speak. Are the others able to build for {Mac, Linux, Windows}?

**Comment by simonvanderveldt** [comment]
> Are the others able to build for {Mac, Linux, Windows}?

AFAIK macOS is generally the problem here, I believe because Apple only allows building on macs. GitHub Actions can do all of these, CircleCI as well but only for the payed version, Travis should be able to do all of these as well in their free offering.
