### ISSUE TITLE
Update Manual

### ISSUE THREAD

**Issue by TheWaveWarden** [TheWaveWarden/odin2#316]
see `change_log.md` for new features (LV2 version, Playmodes, many more)

**Comment by pdesaulniers** [comment]
Also, you might want to replace the word "freeware" with "free software" in the manual: https://github.com/TheWaveWarden/odin2/search?q=freeware

The term "freeware" typically refers to proprietary software which is free to use :)

**Comment by xard-dev** [comment]
The PDF manual version 2.2 also has **Osc FM amount** listed twice page 59 instead PM as the row content suggests.

**Comment by TheWaveWarden** [comment]
Updates needed:
- [x] LV2 version
- [ ] Play modes
- [ ] Microtuning
- [ ] Reverb
- [ ] New panel overview
- [ ] Breath modulation source
- [ ] FM-PM ranges

more? This list was generated from
