### ISSUE TITLE
build fail with latest pull

### ISSUE THREAD

**Issue by davephillips** [TheWaveWarden/odin2#319]
Build fails here:

```
Compiling Utilities.cpp
../../Source/Utilities.cpp: In member function ‘void Utilities::writeSampleTableToFile(const string&)’:
../../Source/Utilities.cpp:1214:97: error: request for member ‘get’ in ‘file.juce::File::createInputStream()’, which is of pointer type ‘juce::FileInputStream*’ (maybe you meant to use ‘->’ ?)
  AudioFormatReader *audioFormatReader = wavAudioFormat.createReaderFor(file.createInputStream().get(), true);
                                                                                                 ^~~
Makefile:416: recipe for target 'build/intermediate/Debug/Utilities_707bb76b.o' failed
```
 - OS: Linux
 - Ubuntu 18.04
 - VST/ LV2

I hope that helps. Please advise if other information is needed.

Best regards,

Dave Phillips

**Comment by KottV** [comment]
Hi,

What is JUCE version you use?

**Comment by TheWaveWarden** [comment]
The most recent JUCE version seems to be outputting a unique_ptr here. See the docs:

https://docs.juce.com/master/classFile.html#a005e70f81272e0bf30563b96665065da


Anyway you have two options: 
- Downgrade to JUCE 6.0.1
- just replace that `file.createInputStream().get()` with `file.createInputStream()->get()` and you should be good to go

**Comment by TheWaveWarden** [comment]
On a different note, I might remote that `Utilities.cpp` compile unit from the build entirely, as it only contains stuff which was needed to generate wavetables and such.

**Comment by davephillips** [comment]
@KottV and @TheWaveWarden : Thanks for your responses, I got it figured out last night. It was the JUCE version, mine was too old. Built Odin2 successfully and tested the standalone. Outstanding work, massive thanks for making it open-source !

Best,

dp
