### ISSUE TITLE
[Feature Request] Separate dirs for Factory and User presets.

### ISSUE THREAD

**Issue by KottV** [TheWaveWarden/odin2#322]
**Is your feature request related to a problem? Please describe.**
On Linux the Odin2 stores all patches in **/opt** folder. This can be problematic for couple of reasons:
1. As Odin2 is opensourced now and there is very possible that it will be packaged by native build systems in vary repositories. Linux filesystems hierarchy means that application data should be stored in **/usr/share** dir (while **/op**t is possible it assumed for completley 3rd-party  software). 
2. /opt and /usr/share is readonly for users.

**Describe the solution you'd like**
Expand patches path into two: Factory and User.
Factory can be taken by:
```
File::getSpecialLocation(File::SpecialLocationType::globalApplicationsDirectory).getFullPathName() + File::getSeparatorString() + "share" + File::getSeparatorString()  + "odin2"
```
And Users:
```
File::getSpecialLocation(File::SpecialLocationType::userApplicationDataDirectory).getFullPathName() + File::getSeparatorString()  + "odin2"
```

**Describe alternatives you've considered**
Make /opt/odin2 writeable for users. This is not default behaviour but will work. Making /usr/share/odin2 writeable is bad idea :)

**Comment by TheWaveWarden** [comment]
Yes, this would be better. The solution right now just is platform agnostic in that we don't need separate locations on mac and win (or do we?). We also need to make sure data is transferred over with the new installer, so people don't lose their current patches.

I had a similar situation on Mac where I moved the presets to a different location and it was a major headache.

> Make /opt/odin2 writeable for users. This is not default behaviour but will work.
This is what's currently happening.

**Comment by KottV** [comment]
Yeah, keeping presets with update will be additional task for this issue...

**Comment by hfiguiere** [comment]
This also would break any kind of sandboxing (I'm thinking of flatpak here). 

Making a directory user writable outside of the user's home directory is considered a bad idea.

**Comment by hfiguiere** [comment]
JUCE has `userDocumentsDirectory` or `userMusicDirectory` which maps to the proper directories depending on the platform.

**Comment by hfiguiere** [comment]
The suggestion of using `userApplicationDataDirectory` also works but I think preset are use data not configuration.

**Comment by KottV** [comment]
There no single opinion where should presets be. Some people really dislike when something appears in **Documents** without asking, while hidden **.config** is ok )

>>The solution right now just is platform agnostic in that we don't need separate locations on mac and win (or do we?). 

As I can see paths for Mac and Win/Lin is different, so it's not so agnostic. I didn't test it in Windows though.
Main problem in Linux is that package managers can't install to user's directories, only system-wide. There can be skeletons in /etc/ for user's profile patterns, but this is overkill imho for synth.

**Comment by hfiguiere** [comment]
> There no single opinion where should presets be. Some people really dislike when something appears in **Documents** without asking, while hidden **.config** is ok )

But then you have to answer the question "How do I copy my presets?".

Either is still way better than the current situation.

**Comment by KottV** [comment]
>>But then you have to answer the question "How do I copy my presets?".

I have no answer yer. Kind of brainstorm needed.

**Comment by KottV** [comment]
Some ideas, not so sophisticated:

1. Add mention about changing preset dir in readme and package description. Let user do the rest.
2. Look for presets in old dir too, while use new paths as default.
3. Copy presets from old dir to the new at start, then set flag in config that it was done. Worst idea imho.

**Comment by ryyzerr** [comment]
I agree that `/usr/share` is ideal for Factory Presets, though `/opt` is also common enough as well imho.

Someone correct me if I'm wrong but wouldn't `~/.local` be the more appropriate place for non-configuration user data?

As for moving the User Presets, I think a combination of KottV's 1 and 2 would work for anyone building from source or using the generic binary package. The distro-specific packages can be scripted to handle the change, or at least that's my current plan for the AUR build.

**Comment by KottV** [comment]
> Someone correct me if I'm wrong but wouldn't `~/.local` be the more appropriate place for non-configuration user data?

From my experience ~/.local is for miscellaneous stuff, which can be safely deleted (and restored with default app settings), though afaik Steam keeps savegames there
Actually we can make a vote or something to set user's dir.

**Comment by TheWaveWarden** [comment]
Apart from the preset-migration, large parts of the patchbrowser will need to be rewritten if patches are split up. This would also be a linux-only change, which is what I meant with it being agnostic.

See class `PatchBrowserSelector`, which is basically one of the three windows in the patchbrowser. It scans a single directory for files/dirs and lists them accordingly.

If the `opt` location is not ok for changed file permissions then I suggest everything is moved to user space, including the Factory Presets. The obvious downside would be that the factory presets are only installed for that user. But it seems nicer to me than frankensteining the whole thing together?

**Comment by ryyzerr** [comment]
Hmm. That is a tough one.

The `/opt` solution isn't a huge issue, but it's definitely not ideal because it doesn't offer any protection, or segregation, of user assets. Some people also get loopy about loose permissions, which I can understand.

On the other hand, moving everything into the users home directory has the opposite problem. It offers protection and segregation of user assets, but no system-wide Factory Presets for other users.
This would also present a problem with package managers, as they don't install things into `$HOME`, that's for the application to do during runtime.

Sounds like it might be best to stick with the `/opt` solution for now imho.

**Comment by KottV** [comment]
I've dig a little and didn't find good solution or example for separate factory/user files.
All JUCE-based plugins that i have keeps their data in user's dir (userApplicationDataDirectory or userDocumentsDirectory).
Another option - is to build in factory presets as binary resources. Not sure how much work it requires but looks like best solution, for a packagers at least.

**Comment by KottV** [comment]
> Sounds like it might be best to stick with the `/opt` solution for now imho.

Yes it works but against packaging policies.
For now i think to slightly modify the code for rpm packages which i build, so Odin2 will use ~/.config

**Comment by TheWaveWarden** [comment]
@KottV thanks for building RPM :-)

**Comment by hfiguiere** [comment]
I package for Flatpak (not submitted yet) but even with patching the code to not use `/opt` the user presets can't be saved because the filesystem is read-only.

So yes there is a good reason to separate the factory presets (read-only) and user presets.

**Comment by KottV** [comment]
@hfiguiere what did you set as user's dir? We need a consensus before provide incompatible versions of Odin.

**Comment by TheWaveWarden** [comment]
There's also an AUR package available

https://aur.archlinux.org/packages/odin2-synthesizer/

This one uses the current `/opt` implementation

**Comment by hfiguiere** [comment]
> @hfiguiere what did you set as user's dir? We need a consensus before provide incompatible versions of Odin.

The only consensus I care here is that the user preset can be saved in a location that is user controlled, different from the factory preset.

I have to patch JUCE anyway because JUCE.

**Comment by baconpaul** [comment]
I think one of the single most opined on features in surge has been 'where does stuff go'. We ended up with a variety of waterfalls and have a lot of assets required to run so it matters.

on mac it is easy. We use either the system or user Library directory for factory assets and the user documents directory for user presets and the like (~/Documents/Surge but with the proper API).

On windows we have two flavors, a portable and a non-portable flavor. The non-portable flavor puts factory assets in %PROGRAMDATA%\Surge and user data in %MY_DOCUMENTS%\Surge (basically). the portable flavor will fall back to that, but before it does so, it looks up the DLL location and checks if there is a directory called "SurgeData" and "SurgeUserData" next to the VST3; If there is it uses those directories. This defacto lets folks put their directories and .vst3 next to each other and move them wherever.

On the variety of configuration choices that constitute the experiences generally know as "the" linux desktop it is a bit more complicated. You can see what we ended up with here (and this, remember, is to find 2 directories - a factory and user data path).

https://github.com/surge-synthesizer/surge/blob/8e03ba0b54b09ca8e26080e9227091e3fd4fd074/src/common/SurgeStorage.cpp#L208

Basically

If $XDG_DATA_HOME/share/surge exists use that
else if ~/.local/share/surge exists use that
else if ~/.local/share/Surge exists use that
else if $CMAKE_BUILD_PREFIX/share/surge exists
else $CMAKE_BUILD_PREFIX/share/Surge
else /usr/share/surge
else /usr/share/Surge
else error

That covers a variety of cases that distros have wanted. Nixos wanted to set CMAKE_BUILD_PREFIX to /g/sadsa or something not /usr, for instance

For user data we found the linux community was of two groups, which I would put in the "of course all home directories contains Documents folder" (as group 1) and "if you create a Documents folder or have one in your home directory You Are Doing It Wrong" (as group 2). These are clearly harder to reconcile :) So we chose the following for the user folder.

1. If ~/Documents/Surge exists use it; if ~/.Surge/ exists use it
2. If neither exists, but ~/Documents exists, create ~/Documents/Surge and use that
3. But if neither exists and ~/Documents does not exist, create ~/.Surge and use that.

Hope this helps! It's been a journey ... but I would say people rarely complain about our choices now.

**Comment by KottV** [comment]
Good info, thanks. IIUC Surge has two variables: datapath and userDataPath. While Odin 2 just one path (for now, maybe).

**Comment by KottV** [comment]
rpms for openSUSE https://build.opensuse.org/package/show/home:geekositalia:daw/odin2 with ~/.config for presets :)

**Comment by baconpaul** [comment]
> Good info, thanks. IIUC Surge has two variables: datapath and userDataPath. While Odin 2 just one path (for now, maybe).

yes exactly. and the intent is datapath is not user writable, and userdatapath is.

**Comment by fpesari** [comment]
Having a user-writable `/opt` directory is problematic on many distros and `/opt` in general is a discouraged practice.

Yoshimi, geonkick and amsynth store presets in `~/.local/share`. What @KottV says is true, `~/.config` is more common but it's roughly equivalent to `/etc/` and as such, meant for configuration. I think that the correct way is to follow *NIX conventions, in this case the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf).

**Comment by baconpaul** [comment]
Over in surge land, like I said, we had a waterfall, but on linux the top of our waterfall was the free desktop spec https://specifications.freedesktop.org/basedir-spec/latest/ar01s02.html which is why we use the XDG variable at the top of the waterfall. $XDG_DATA_HOME defaults to ~/.local/share 

But it's tricky since there is no such thing as "The" linux desktop and there's lots of opinions which is why we added a waterfall.

I think the key here though for surge is throughout the code we maintain a factory-data and user-data path as two separate paths and act accordingly through the code.

**Comment by TheWaveWarden** [comment]
Sorry for not turning to this immediately - this topic seems to be very important to people, but I'm not super keen to grind my teeth into.. I will do it after the reverb is finished probably.

For what it's worth, I like Kotts idea of including the factory soundbank as a binary resource. This way a single path is used for presets. Allthough it would mean to divide the patch browser into a 'path' and a 'binary resource' hybrid. But this doesn't seem more complicated than adjusting for two paths. Another thing to consider would be to build a tree of categories in code and keep it up to date. Probably a bash script generating code from the currently available presets.

However people who previously saved presets inside the "Factory Presets" bank would be out of luck, as their presets get deleted in the transition.

**Comment by baconpaul** [comment]
So ... with tuning-workbench-synth (a JUCE synth we wrote in Surge land to show off our SCL/KBM library (and hey we should talk about that)) I did exactly this. I have presets and include them in the binary. We have a small number so did it in the obvious gross way (https://github.com/surge-synthesizer/tuning-workbench-synth/blob/8d08caa634b8632ef92b2036d334639567ccd133/Source/PluginProcessor.cpp#L240) but would be easy to script.

It reminds me though: Wanna add SCL/KBM support to odin? We have a library which does it if you do. But that's a separate issue. Hit me up in an issue here or on discord and I can explain if you want.

**Comment by KottV** [comment]
Loomer and Pianoteq uses ~/.local/share too.
Dilemmas :facepalm: 

My point of view: As was mentioned ~/.config is kind of local /etc. And /etc is the very important directory which contains passwords, server's certificates, global configs. Deleting this dir will mostly kill your system.  I believe that user's presets is result of work, and not app's some data. So personally I'd like to keep presets in the place which user is care of: .config (or Documents).

**Comment by plaimbock** [comment]
I patched Odin2 so it uses ~/.TheWaveWarden/odin2/ where the config is saved. I symlink /opt/odin2/Soundbanks/User\ Patches to ~/.TheWaveWarden/odin2/Soundbanks/User\ Patches. When a new version/commit with fix is released I rebuild my RPMs and update which does not touch anything in ~/ I've done this also for OB-Xd, Surge and Dexed.

**Comment by plaimbock** [comment]
> I think the key here though for surge is throughout the code we maintain a factory-data and user-data path as two separate paths and act accordingly through the code.

That was a nice design, thanks! Would appreciate it if Odin2 had something similar.

**Comment by baconpaul** [comment]
> I've done this also for OB-Xd, Surge and Dexed.

I am surprised this requires a surge patch, since user selectable user folders has been a feature since Surge 1.6.3 or so. What did you need to patch?

**Comment by plaimbock** [comment]
> > I've done this also for OB-Xd, Surge and Dexed.
> 
> I am surprised this requires a surge patch, since user selectable user folders has been a feature since Surge 1.6.3 or so. What did you need to patch?

I created the patch when switching a lot between pre-built Surge and self-built Surge. Not sure why any more but maybe for the symlink check.
```
/* always use datapath = /usr/share/surge/ */
std::string systemDataPath = std::string() + "/usr/share/surge";
datapath = systemDataPath;
```

```
/* always use userDataPath = ~/.Surge */
std::string dotSurge = std::string(homePath) + "/.Surge";
if (!fs::is_directory(string_to_path(dotSurge)) || !fs::is_symlink(string_to_path(dotSurge)))
{
      fs::create_directories(string_to_path(dotSurge));
}
userDataPath = dotSurge;
```

**Comment by TheWaveWarden** [comment]
> I patched Odin2 so it uses ~/.TheWaveWarden/odin2/ where the config is saved. I symlink /opt/odin2/Soundbanks/User\ Patches to ~/.TheWaveWarden/odin2/Soundbanks/User\ Patches. When a new version/commit with fix is released I rebuild my RPMs and update which does not touch anything in ~/ I've done this also for OB-Xd, Surge and Dexed.

Ok cool! Please keep in mind that you will have to migrate patches from your location to the official location once my changes roll out or users will lose their patches with the upgrade

**Comment by TheWaveWarden** [comment]
@KottV @plaimbock @hfiguiere @ryyzer 

I am starting work on this right now. The current plan is to move factory presets to the binary and change the location of user presets (and the `odin.conf file) to somewhere in the homefolder. This way all data that is currently being installed will be contained within the VST3 file. All other data that is generated by the user after application start will be in the users homefolder.

Candidates for the actual location are `~/Documents/odin2`, `~/.config/odin2` or  `~/.local/share`, maybe with a waterfall option, like mentioned for Surge.

Is this a solution that every package manager / distro can work with? Also keep in mind that the packages will need to migrate all existing presets from `/opt/robodev` to the new location in userspace.

**Comment by KottV** [comment]
>Is this a solution that every package manager / distro can work with?

Speaking of myself and **rpm** - yes, absolutely.

**Comment by hfiguiere** [comment]
That would work.

**Comment by basschaser** [comment]
@ryyzer here. Had a name change, sorry for any confusion, and the very late reply.

> Candidates for the actual location are ~/Documents/odin2, ~/.config/odin2 or ~/.local/share, maybe with a waterfall option, like mentioned for Surge.

Any of the above choices would work, I personally would suggest `~/.config` or `~/Documents/odin2` though.

`~/.local` typically tends more towards being a sort of temp directory, and a user may not expect important personal files to be there (I don't back up that directory at all, myself, because there's nothing important in there).

> Is this a solution that every package manager / distro can work with? Also keep in mind that the packages will need to migrate all existing presets from /opt/odin2 (or wherever you stored them) to the new location in userspace.

The only hangup is that package managers on Linux typically do not touch the user's home directory. They run as root, with no awareness of the user, and install applications globally. There is no problem with the application storing data there, but migrating data using the package manager is, unfortunately, not possible.

Therefore, the application will have to handle the migration, or the user will have to be notified so they can do it manually. Unfortunately, I am not aware of any other way around this issue.

**Comment by TheWaveWarden** [comment]
@basschaser I managed to pack the migration into a debian package by using a post install script. This is run as root, but you can see who installed it via environment variable `SUDO_USER` (assuming they're using sudo rather than being root). From that I can copy data and set permissions for the user:
https://github.com/TheWaveWarden/odin2/blob/devel/installers/linux/create_deb_package.sh#L57-L65

**Comment by basschaser** [comment]
Interesting, this should work for me as well!

I'm not sure how prevalent it is on Debian systems, but on Arch we will also need to account for the edge case of a user using `doas`, rather than `sudo`. Luckily, this is fairly simple as `doas` appears to have a similar variable `DOAS_USER`.
