### ISSUE TITLE
[Feature Request] Allow more range in the modulation matrix

### ISSUE THREAD

**Issue by unfa** [TheWaveWarden/odin2#330]
Currently to get a satisfying kick drum pitch envelope I had to assign the same envelope to my Sine Oscillator three times (total modulation amount of 300).

It'd be fantastic if the modulation matrix would have a x10 modulation switch for each destination, or simply allow ranges beyond -100 / +100, but maybe go up to a -1000/+1000.

I think a great tool should allow artists to do things that might not seem reasonable at first, but in some corner cases, such possibilities allow us to create amazing sounds. So many amazing developments in music and sound design came from abusing hardware and software - starting with The Beatles overloading a mixer preamp to create harsh guitar distortion.

Please - give us more range!

**Comment by TheWaveWarden** [comment]
I'll look into it - I see increasing the handling to +/-N00 more feasible than a x10 button for layout reasons.

The big thing to keep in mind here is to let things blow up. This should be happening already.

Also, I think scaling would need to stay at +/-100, but that's ok.

**Comment by TheWaveWarden** [comment]
@unfa 
![image](https://user-images.githubusercontent.com/28705282/97606476-1fc90a00-1a10-11eb-95a9-96a68117f648.png)

**Comment by TheWaveWarden** [comment]
@unfa 
https://thumbs.gfycat.com/GravePaleDwarfmongoose-mobile.mp4

Colors subject to change
