### ISSUE TITLE
[Feature Request] Set the filer cutoff to neutral (highest) value in the Init patch

### ISSUE THREAD

**Issue by unfa** [TheWaveWarden/odin2#331]
Right now Odin2 starts out with a lowpassed sawtooth.

It has happened to me hat I forgot to turn the lowpass filter up, and I failed to notice what was making my sound so muffled.

I think it'd be easier to work with Odin2 if the cutoff was dialed all the way up where it doesn't affect the sound.

What do you think?

**Comment by TheWaveWarden** [comment]
I think it's a matter of taste. A plain sawtooth can be very unpleasant to the ears. But I am open to what others have to say :-)

**Comment by unfa** [comment]
That's true, though many synthesizer do use a plain Saw wave as the Init patch. Another approach could be to make the default a sine wave, like in ZynAddSubFX / Zyn-Fusion. I honestly like that idea a lot, as it's literally starting with a patch with the simplest sound possible.

**Comment by xard-dev** [comment]
Sine wave default with no filter would be quite good compromise for the default sound.

The filtered saw wave is quite nice choice in terms of audio. However having done whole set of presets for one song from scratch I can also agree that the filter is easy to forget.

**Comment by TheWaveWarden** [comment]
Sine wave with no filter not that optimal IMHO: It's a subtractive synth and most patches subtract content from a wave, which in most cases will be a saw. Therefore extra clicks are needed to get to what is used in 70% anyways. Also for newbies it is nice to have a filter to draw your gaze from the get-go, so they see where filters are located and how they function.

Anyway, lets poll this:
- :+1: Saw with closed filter (as is right now)
- :100: Saw with open filter
- :1st_place_medal: Sine with no filter

**Comment by sandycorzeta** [comment]
> I think it's a matter of taste. A plain sawtooth can be very unpleasant to the ears. But I am open to what others have to say :-)



> Right now Odin2 starts out with a lowpassed sawtooth.
> 
> It has happened to me hat I forgot to turn the lowpass filter up, and I failed to notice what was making my sound so muffled.
> 
> I think it'd be easier to work with Odin2 if the cutoff was dialed all the way up where it doesn't affect the sound.
> 
> What do you think?

i agree with this. Considering that most popular modern commercial synth plugin found on music production nowadays are using saw init with no filter applied by default. 

By using clean saw with no filter as default init patch. We follow a good practice, and that helps the familiarity to the users coming from another synth to use Odin2.

**Comment by TheWaveWarden** [comment]
Ok, I will move the filter cutoff to max position with the next release!

**Comment by TheWaveWarden** [comment]
https://github.com/TheWaveWarden/odin2/commit/e6615e2693b7d3d5a898896b2e354b726aa4fe30
