### ISSUE TITLE
[Feature Request] Drag'n'Drop modulation assignement

### ISSUE THREAD

**Issue by unfa** [TheWaveWarden/odin2#332]
The Odin2 workflow could be sped up significantly if the modulation sources (LFOs, ENVs and other) could be assigned to modulation targets by drag-and-drop.

Right now the user needs to menu-dive in the Modulation Matrix to make assignments, which seems like a sub-optimal way of doing this.

What do you think?

**Comment by TheWaveWarden** [comment]
This was requested very often. However, I don't think it is going to be a thing: In order to implement this properly, one would need to have some kind of handle (like in Helm), for which I dont see the GUI space to do it consistently across all modules.

I'm leaving this issue open for now in order to allow for some discussion / ideas.

**Comment by unfa** [comment]
That's true, probably some UI layout changes would be necessary, and that's never fun to do.

**Comment by mkruselj** [comment]
Probably no need for UI layout changes for most of the sources.

For LFOs and envelopes I bet you can make the actual tabs draggable onto the target of your choosing. For PB/MW you could make the text labels next to wheels draggable. For XY you could make X and Y labels draggable. For osc/filter outs you could make the text label of the particular osc or filter draggable. For unison stack you could make the Unison button draggable. Similar for arp mod 1/2.

So the only things that would require then visiting the menus are keytracking, aftertouch, velocity, pedals, random and constant.

**Comment by TheWaveWarden** [comment]
I am just sorting through issues. Sadly, this feature is not going to appear in the near future, sorry.
