### ISSUE TITLE
[Bug Report] Unresponsive GUI in Bitwig on Linux (VST3)

### ISSUE THREAD

**Issue by ryyzer** [TheWaveWarden/odin2#335]
**Describe the bug**
When the plugin is first loaded, the GUI is visible but completely unresponsive by mouse. The GUI *can* be manipulated by moving the knobs in Bitwig's "Device Panel". 
When closing the plugin window, and trying to open it again by clicking "Show Plugin Window", the window does not render properly. Only the border is rendered, the window content itself is non-existent/transparent.

**To Reproduce**
1. Load Odin 2 (VST3) plugin in Bitwig
2. Try to move the knobs in Odin 2 GUI
3. Close plugin window, and reopen it by clicking "Show Plugin Window"

**Expected behavior**
Expected the GUI to respond, and knobs to move like they do in other plugin hosts, or running as a standalone.

**Screenshots**
[Here](https://ibb.co/Hd290VV) is an example of the non-rendered window.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Odin 2.2.4 / Bitwig 3.1.2
 - Plugin Format: VST3

**Additional context**
This is a consistent behavior - it happens reliably when using Bitwig. This behavior is not present when running the plugin as a standalone, or in Reaper.

**Comment by TheWaveWarden** [comment]
Ayyy, setting up Arch will cost me a week to reproduce this...

Just joking; I'll look into it. I've seen this on UbuntuStudio 20.04 before.

**Comment by baconpaul** [comment]
@TheWaveWarden just FYI that's a pretty old Bitwig version and their linux VST3 support matured a lot over the last 6 months. With surge we found we had to get to 3.2 vintage to be reliable (and there's a bug in more-recent-than-3.2.4 with keyboard in sandboxed mode). Our Tuning Workbench Synth (which is Juce6) didn't work reliably until 3.1.4 or so if I recall. I wonder if OP upgrading bitwig could help also?

**Comment by TheWaveWarden** [comment]
Reproduced in Ubuntu 18.04, Bitwig 3.1.3

**Comment by TheWaveWarden** [comment]
@ryyzer I was consistently able to reproduce this issue on a number of distros on Bitwig 3.1.3. The same happens with Surge-FX (which uses a completely different framework). The issue dissappeared when I upgraded Bitwig to 3.2.8. Therefore, I am pretty certain the issue is with Bitwig not Odin.

Can you please upgrade Bitwig and confirm?

**Comment by baconpaul** [comment]
yeah 3.1.3 had definite VST3 bugs with painting. If you look at 3.2.0 changeling you can see that's when we got surge running :) https://downloads-na.bitwig.com/stable/3.2/Release-Notes-3.2.html

(If you are really interested in the innards of the linux vst3 runloop I'm happy to share what we had to change in surge and what bitwig shifted to get it working in 3.2 vintage).
