### ISSUE TITLE
[Bug Report] Missing fonts on Arch Linux (VST3)

### ISSUE THREAD

**Issue by ryyzerr** [TheWaveWarden/odin2#336]
**Describe the bug**
When moving a knob in the plugin window, the popup/tooltip containing the parameter value does not render its font correctly. Other values in the plugin window also don't display correctly. Only boxes are shown instead.
In my experience, this is probably due to a missing runtime dependency for some Font Family.

**To Reproduce**
1. Open the plugin and move a knob
2. See the missing fonts in the tooltip/popup

**Expected behavior**
Expected to see a clearly rendered value for the knob

**Screenshots**
[Here](https://ibb.co/7YCLxTY) is an image showing the missing fonts

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 2.2.4
 - Plugin Format: VST3

**Additional context**
This happens happens consistently in Reaper, and with the standalone plugin.

**Comment by xard-dev** [comment]
Hmm... I think that those tooltips rendered using JUCE default style (I might be wrong but at quick glance it looks very much like this would be the case). 

Have you seen similar problems for other JUCE plugins like OB-Xd?

**Comment by ryyzerr** [comment]
SOLVED: Install `ttf-dejavu` fonts from the official Arch repositories. Other font packages such as `ttf-liberation` or `ttf-ubuntu-font-family` may also work here. I'm creating a PKGBUILD of Odin 2 for the AUR, so I will investigate this further and set dependencies accordingly.

I can't speak for other JUCE plugins, as I don't have any. It seems that you're probably correct though, and my system was just lacking in proper font coverage. @xard-dev
