### ISSUE TITLE
[Feature Request] Suggestions for a “scene”-system

### ISSUE THREAD

**Issue by bent95** [TheWaveWarden/odin2#338]
Odin 2 has become one of my favorite synthesizers because of how it is at the same time user-friendly, feature-rich, and has great sound. However there is one thing that bothers me: When creating layered or evolving patches I often “run out of space”, wishing I had more oscillator slots, envelopes or similar to play with. And I imagine that as Odin 2 gains more features this will become an even bigger issue.

Surge, a synthesizer that is in many ways comparable to Odin 2, has solved this by having two “scenes”, which are essentially separate instances of Surge’s oscillators and filters. They can be switched between with the click of a button, but are unable to interact with each other in any way. They are added together at the effect-stage, so that they can share effects such as delay or chorus if so desired.

I think Odin 2 would benefit immensely from having something similar, but of course adapted to fit the general design of the synth. Here is how I imagine it:

![Odin1](https://user-images.githubusercontent.com/46249598/97246317-5aa72400-17fd-11eb-8a14-12cf13ca16a4.jpg)

The default patch would look and act completely identical to before – the only thing different being the four new buttons to the right of the top logo: “Scene1”, “2”, “3” and “Out”; because things in Odin tend to come in threes, it would only make sense for there to be three scenes as well.

Scene two and three would be empty by default, but be functionally identical to scene one, with their own private oscillator slots, filters, modulation matrices, effects, etc.. 

The out-scene is where it gets really interesting: 

![Odin3](https://user-images.githubusercontent.com/46249598/97246389-85917800-17fd-11eb-9aea-75f350de3e56.jpg)

Being a fully featured scene in and of itself, and responsible for outputting sound to the DAW; scene 1-3 would be available here in the form of oscillators, to be used just as you would any other oscillator.

I think having such a system would really add to the flexibility of the synth without creating more complexity or visual clutter.

Unfortunately I lack the C++ skills to be able to implement this myself, and I suspect that will be the case for some time. But I thought I’d throw the idea out there just in case someone finds it interesting. And finally: Thanks for the great instrument!

**Comment by TheWaveWarden** [comment]
Hi @bent95 , thanks for the time and thought you have put into this.
It is an intriguing system, but I don't see it happening for now. My main concerns are:
- restructuring at the very heart of the synth required to pull this off
- performance: This would essentially triple the load of the synth at any point
