### ISSUE TITLE
No GUI visible  in Ardour 6.3

### ISSUE THREAD

**Issue by alasta4204** [TheWaveWarden/odin2#339]
GUI fails to load Synth is running and default tone audible 
**To Reproduce**
1. Load synth plugin
2. Double click on synth in track 

*Ubuntu  20.04 Studio  LV2]

Window opens but no GUI Visible
![ODIN Synth_2020-10-27_13-48-36](https://user-images.githubusercontent.com/44087152/97310593-4d208700-185b-11eb-9eea-9746f777ee0f.png)

**Comment by xard-dev** [comment]
One thing which would be good to confirm: you do seem to have other plugins in the project. Have you tried having Odin2 as only plugin in the whole project? 

This is to rule out certain new JUCE vs older JUCE related bugs I've encountered which can result in black windows.

**Comment by alasta4204** [comment]
Here we go , works on its own . The other plug in you see in the project is
Tone Lib GFX a guitar amp simulator . When I try and load that Ardour Exits
to the desktop on the first occasion the second time I try   it Odin
corrupts its GUI. Running on its own ODIN has exited to the desktop on two
occasions whilst browsing presets

**Comment by xard-dev** [comment]
@alasta4204 yes, looks like very same issue I had with current stable Helm and newer JUCE plugins. I managed to fix Helm by upgrading the JUCE and making a pull request from it.

**Comment by trebmuh** [comment]
Quickly mentioning here that I'm running Odin2 (self-compiled) on Ardour 6.3 on LibraZiK 3 (Debian Stable) and the GUI is showing fine.

**Comment by TheWaveWarden** [comment]
> @alasta4204 yes, looks like very same issue I had with current stable Helm and newer JUCE plugins. I managed to fix Helm by upgrading the JUCE and making a pull request from it.

From which version to which did you upgrade Helm?

**Comment by alasta4204** [comment]
Thanks for your help everyone. I have tried Odin with various other  plugs and  its behaving properly with no  issues . Seems that Tone Lib FX is the cause ( a commercial plugin  with some nice presets which set me back $39 ) This needs setting to resolved I reckon (my version of HELM works fine which is just as well as  I havent  a clue how to upgrade JUCE :)

**Comment by TheWaveWarden** [comment]
Great, glad you're up and running!

**Comment by xard-dev** [comment]
@TheWaveWarden that's a good question and after some digging on current master Helm sources it seems that the prolematic JUCE version is **5.3.2**. 

There might be other problematic JUCE versions but that is at least confirmed to cause issues when 3d acceleration is used.

**Comment by xard-dev** [comment]
@alasta4204 JUCE is compiled as part of the plugins so unfortunately you pretty much can't update it unless you have access to the source code.
