### ISSUE TITLE
[Feature Request] Reverb Module

### ISSUE THREAD

**Issue by sandycorzeta** [TheWaveWarden/odin2#340]
It would be nice if there is a reverb module in the fx section. Having only delay seems a bit limited

**Comment by unfa** [comment]
Zita-rev1 could probably be a sourced for a really well sounding reverb code.

**Comment by TheWaveWarden** [comment]
@unfa do you have any sound examples for zita-rev1? If you know about other GPL reverbs also feel free to drop them here.

**Comment by sandycorzeta** [comment]
@TheWaveWarden there is also Dragonfly Reverb. Its a reverb suite with 4 type of reverb. Licensed in GPL 3.0. https://github.com/michaelwillis/dragonfly-reverb

**Comment by unfa** [comment]
I use Dragonfly Reverb all the time, but - there's a bug somewhere in it that occasionally creates huge volume spikes and causes audio path to be overloaded with NaNs or something. That's why for stability's sake I'd recommend Zita-Rev1 or Mverb as bases.

**Comment by xard-dev** [comment]
@unfa that Dragonfly Reverb problem seems to happen for me especially when I leave any effect value to down to 0%: Save, reload and BOOM.

Calf reverb has very audible highs but is metallic and harsh (aliased?).

Zita-Rev1 is not as rich as Dragonfly but the resource usage is low and I haven't had any stability problems with it. 

If I recall correctly Zynaddsubfx uses freeverb. Also could check what approach Helm uses for reverb...

**Comment by TheWaveWarden** [comment]
I listened to both Dragonfly and Zita-rev1. While Dragonfly (Suite) seems do be able to do everything, I was more drawn to zita. Hardly any setting sounding bad, feels like a "Cathedral" space. Suits the synth well IMHO.

I will look into the zita-rev1 code and see how hard integration would be

**Comment by xard-dev** [comment]
That seems very reasonable approach as Dragonfly and other more versatile reverbs can be added in the post processing for those special cases needing it.

One special request I do have for the reverb: pretty please with a cherry on top consider adding ducking to it!

It's so weird that most reverbs do not have that while it's essential for getting really space effect without muddying the dry sound.

**Comment by TheWaveWarden** [comment]
> One special request I do have for the reverb: pretty please with a cherry on top consider adding ducking to it!

Good idea. Also the ducking is in place for the delay module already, so I can reuse code. The only thing standing in its way might be GUI space. Assuming I keep at least one of the EQs in the reverb, that's eight knobs already. Plus ducking would make it nine. The space would be the same as for the other FX modules.

Surprisingly, the EQs **really** added to the atmosphere in zita, kinda impressed by the overall quality of the thing.

**Comment by xard-dev** [comment]
Argh... it would be such a shame if layout space would be the reason not to include the ducking.

In ardour I've created a single track with complete 4 channel internal routing for Dragonfly reverb which is controlled with dry side compression where the audio will finally be routed back to stereo to deal with this. This of course enables a full control of the whole thing but for basic cases the solution is so overkill.

**Comment by baconpaul** [comment]
@TheWaveWarden if you're interested, Surge's "reverb2" is a pretty darned clean implementation of the 'network of APF' reverb and is a small bit of relatively simple code.

**Comment by TheWaveWarden** [comment]
@baconpaul I spent some hours trying to get zita-rev1 to work in odin, but it keeps blowing up in my face. I just took your reverb2 for a testdrive (Surge-FX really coming in handy here) and it soulds very nice. I'll take a look at your code tonight and use yours over zita, if possible. I'll build in an EQ of sorts though.

So you get filters, I get a reverb. I am just now realising how great this whole open-source thing really is :D

**Comment by baconpaul** [comment]
Ha yeah! Indeed!

**Comment by baconpaul** [comment]
Just hit me up on discord if you have any questions - https://github.com/surge-synthesizer/surge/blob/main/src/common/dsp/effect/Reverb2Effect.cpp there's the code and *f is just the parameter array. Probably need a bit of a re-work but nothing too extreme.

**Comment by KottV** [comment]
Is the reverb planned for 2.3 release?
I'm playing with devel branch and see that reverb controls are out of box in 100% size, on 150% it draws fine:

![изображение](https://user-images.githubusercontent.com/4686351/109591560-7464c900-7b59-11eb-8e1b-6c2410eeaf18.png)

**Comment by TheWaveWarden** [comment]
> Is the reverb planned for 2.3 release?
> I'm playing with devel branch and see that reverb controls are out of box in 100% size, on 150% it draws fine:
> 
> ![изображение](https://user-images.githubusercontent.com/4686351/109591560-7464c900-7b59-11eb-8e1b-6c2410eeaf18.png)

Yes, it's not in a usable state right now. I'm planning to add two reverbs actually: Zita-rev1 and Surge Reverb2.

The 100% on devel is broken right now, yes. The GUI layout is far from finalized and I am testing on 150%. I should probably make it a habit of developing features on separate branches and merging them onto devel when they're finished.
