### ISSUE TITLE
[Bug Report] Release get cutted off when Unison is used more than 1

### ISSUE THREAD

**Issue by sandycorzeta** [TheWaveWarden/odin2#341]
**Describe the bug**
Im trying to make a simple pad patch but unfortunately, raising the unison for more than 1 made the release get cutted off even i raise the fader up.

**To Reproduce**
1. Load synth plugin
2. Click on 'reset synth'
3. Draw and Play a chord sequence
4. Change the Unison to 3 or more
5. Raise the attack and release
6. Sound get cutted off.

**Expected behavior**
Release shouldn't get cutted when changing notes even Unison is set to more than 1.

**Video**
[https://streamable.com/nlhh3y](https://streamable.com/nlhh3y)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - DAW being used [Reaper]
 - Odin Version [e.g. 2.2.4]
 - Plugin Format [VST3]

**Comment by TheWaveWarden** [comment]
You're running out of notes. Odin has 24 voices. When Using unison = 3, one note is actually playing three voices. By using rich chords, like in your video with long release times, the notes are still played when the next chord is played. The next chord has priority and steals the notes from the previous once the count gets over 24. This is intended behaviour.


You could compile the synth yourself and change this line to a higher value:
https://github.com/TheWaveWarden/odin2/blob/eab71a940a049700e940038b650e8307bbae3ed0/Source/GlobalIncludes.h#L66

**Comment by sandycorzeta** [comment]
> 
> 
> You're running out of notes. Odin has 24 voices. When Using unison = 3, one note is actually playing three voices. By using rich chords, like in your video with long release times, the notes are still played when the next chord is played. The next chord has priority and steals the notes from the previous once the count gets over 24. This is intended behaviour.
> 
I understand if its intended behaviour as it is.

> You could compile the synth yourself and change this line to a higher value:
> 
> https://github.com/TheWaveWarden/odin2/blob/eab71a940a049700e940038b650e8307bbae3ed0/Source/GlobalIncludes.h#L66

But, instead of compile it by myself. Would you kind to add this functionality in the next update as a feature? Just like in Sylenth, you can set the voice per oscillator and limit the number of polyphony too.

![sylenth](https://user-images.githubusercontent.com/4186454/97431967-22920500-1913-11eb-9105-c2e0e7282444.PNG)

**Comment by TheWaveWarden** [comment]
I already upped the voice count from 12 to 24. The result is people using 4x unison and complaining that Surge has better performance ;-) Upgrading the voice count further has other issues as voices are not created dynamically but exist on the stack.

Your proposed solution of making it user-changeable is preferred of course, but needs some considerable reimplementation. I don't see this happening at the moment, sorry.
