### ISSUE TITLE
Arch Linux / Manjaro Linux has an easy way to install Odin2 now via AUR

### ISSUE THREAD

**Issue by unfa** [TheWaveWarden/odin2#342]
Someone has created and published a PKGBUILD script that'll allow Arch and Manjaro Linux users (or any other Linux distribution that has access to the Arch User Repository a.k.a AUR) to install the synth with a single command!

https://aur.archlinux.org/packages/odin2-synthesizer/

**Comment by TheWaveWarden** [comment]
This is an issue?

**Comment by unfa** [comment]
No, just an information - maybe it'd be good to mention this on Odin2's website?
Sorry if this is the wrong place to report this kind of stuff...

**Comment by TheWaveWarden** [comment]
> 
> 
> No, just an information - maybe it'd be good to mention this on Odin2's website?
> Sorry if this is the wrong place to report this kind of stuff...

No worries, haha. An rpm package is in the works as well. It should also be possible to get the deb package into some repository. I'm not too familiar with these things.

Once it's all done I will definitely add it to my website!

**Comment by unfa** [comment]
Fabulous! Thanks
