### ISSUE TITLE
Question: 32 bits build possiblility

### ISSUE THREAD

**Issue by trebmuh** [TheWaveWarden/odin2#343]
I'm wondering if a 32 bits build can be done currently. More precisely on Linux.
We can see on the [web page](https://www.thewavewarden.com/odin2) that only 64 bits build are available.

_PS: by the way, note that the "Richard Semper" link is broken in the page mentioned above_

**Comment by TheWaveWarden** [comment]
@trebmuh its probably possible. I tried to do it once but moved on when I couldn't figure it out in an hour or so.

**Comment by TheWaveWarden** [comment]
@trebmuh does this help? To clarify, I am not going to work on this. Someone else has to, then maybe we can merge it in here.

If no more questions then please close the issue :-)

**Comment by trebmuh** [comment]
@TheWaveWarden : thanks for clarifying it.
I've got no time to dive in this.
If that happens in the futur, be sure I'll PR it against this repo.
