### ISSUE TITLE
[Bug Report] Retrigger mode restarting ADSRs from zero, rather than current value

### ISSUE THREAD

**Issue by TheWaveWarden** [TheWaveWarden/odin2#345]
**Describe the bug**
Retrigger mode starts the envelope from zero, rather than the current value, thereby introducing clicks

**Screenshots**
Surge has a similar issue with a graphic describing the issue:
https://github.com/surge-synthesizer/surge/issues/824

**Comment by baconpaul** [comment]
Ha I just saw this title and was going to pop over here to say "oh we have an issue with a nice graphic" :)

**Comment by TheWaveWarden** [comment]
@baconpaul haha thanks

**Comment by TheWaveWarden** [comment]
777cb0004bbc4a27bcf7f31f8a914b07af2e806d
