### ISSUE TITLE
Error in LV2 manifest makes plugin unfindable

### ISSUE THREAD

**Issue by caelia** [TheWaveWarden/odin2#346]
I've installed Odin2 on 2 Linux machines, and find that hosts (e.g. Ardour) cannot find the LV2 plugin.

I have traced the problem to `manifest.ttl`, which contains several references to `Odin2_.so` and `Odin2_.ttl`. Note the underscores; the actual files installed on my system do not have underscores in their names.

And the above problem apparently originates in `LV2.mak`, which contains the line:

    JUCE_TARGET := Odin2_

Simply removing this underscore does not seem to solve the problem, since the name with underscores is evidently used in the build process.

**Comment by TheWaveWarden** [comment]
To clarify: Removing the underscores doesn't solve the problem when adjusting manifest or when recompiling the plugin?

**Comment by caelia** [comment]
> To clarify: Removing the underscores doesn't solve the problem when adjusting manifest or when recompiling the plugin?

I meant that changing `LV2.mak` to read `JUCE_TARGET := Odin2` causes compilation to fail.

If I remove the underscores in the installed manifest (`/usr/lib/lv2/Odin2/manifest.ttl`), those references then match the actual filenames, and the plugin becomes visible to LV2 hosts. So I suppose the solution is to generate `manifest.ttl` without the underscores, but I don't know the right way to do that.

Does that make sense?

**Comment by TheWaveWarden** [comment]
Regardless of the final solution, I suggest we fix the AUR before the next release, which might be some weeks in.

@ryyzer can you take a look at this?

**Comment by ryyzer** [comment]
@caelia @TheWaveWarden 

I've just uploaded a new release of the PKGBUILD with the underscores intact. Caelia, I've replied to your comment on the AUR page as well, please let me know if it works for you now!

**Comment by TheWaveWarden** [comment]
Cool, thanks a bunch!
