### ISSUE TITLE
Custom Install Directory [Feature Request]

### ISSUE THREAD

**Issue by daveshow07** [TheWaveWarden/odin2#348]
There is no option to choose a custom install directory in the Windows installer. I use a custom folder for VSTs and plug-ins, and I'd like to install to that directory.

I would like the option to change the vst3 install directory in the Windows installer.

I'm using Ableton Live 9 Suite.

**Comment by mkruselj** [comment]
Live 9 doesn't support VST3 anyways, you need Live 10.1 at the least.

Also VST3 by default requires to be installed in Program Files\Common Files\VST3, and pretty much all DAWs expect VST3s to be there.

**Comment by daveshow07** [comment]
Shoot didn't realize Live 9 doesn't support vst3. 

Thanks!

**Comment by TheWaveWarden** [comment]
Yes exactly like stated above. That's why I hardcoded it.
