### ISSUE TITLE
No files when installing. Ghost install. 

### ISSUE THREAD

**Issue by fabyouda** [TheWaveWarden/odin2#350]
Impossible Installing Odin II on my MacOs Mojave
The .pkg isn't giving any usful folder.

Found the folder VST3 with terminal and Components seams the right one, but isn't applying right. 
![Screenshot 2020-11-06 at 22 48 22](https://user-images.githubusercontent.com/74071827/98418092-7bd00600-2082-11eb-946a-8ca27f2fb732.png)

....

**Comment by TheWaveWarden** [comment]
@fabyouda hmmm that's weird. Could you issue the command
```
ls -l /Library/Audio/Plug-Ins/Components
```
in a terminal and post the output here?

**Comment by fabyouda** [comment]
yes , but it gives this result and I don't know what to get out of it .

total 0

drwxr-xr-x  3 root  wheel  96 Oct 22 17:33 Odin2.component


Il giorno ven 6 nov 2020 alle ore 23:26 TheWaveWarden <
notifications@github.com> ha scritto:

**Comment by TheWaveWarden** [comment]
@fabyouda thanks for reporting back!

I just tried to reproduce the issue and found the problem: You tried to load in the Odin2.component file. This is not a VST or VST3 plugin, but an AudioUnit version, as it is used in other DAWs on Mac.

Odin2 on Mac gets installed as a VST3 and AudioUnit plugin. From what I see, LMMS supports neither VST3 nor AU, sorry.
