### ISSUE TITLE
[Bug report] VST not loading under traction waveform 11 on linux

### ISSUE THREAD

**Issue by I-dont-need-name** [TheWaveWarden/odin2#354]
The plugin doesn't load. Waveform says: the following files appeared to be plugin files but failed to load correctly.

1. install with installation script (I also tried building from source and result is the same )
2. go to plugin setting in Waveform 11
3. click on "Scan for new or updated VST plugins"
4. See Error

 - OS: Arch Linux
 - Traction Waveform 11 free
 - Odin Version 2.2.4
 - Plugin Format VST3

**Comment by TheWaveWarden** [comment]
@I-dont-need-name I get the same error, but also with all other VST3 plugins. Are you certain Waveform supports VST3 on linux? I couldn't find any definitive sources on it.

It seems to me that Waveform recurses the .vst3 files (which are actually directories), finds the Odin2.so in there and tries to open it as VST2 plugins:

![Screenshot from 2020-11-10 16-05-39](https://user-images.githubusercontent.com/28705282/98691870-c9908b00-236e-11eb-9e39-d730320b1c0e.png)

Notice all the other VST3 plugins which show the same error.

**Comment by I-dont-need-name** [comment]
> Are you certain Waveform11 supports VST3 on linux?

Not sure about that. It does support VST3 on Windows and Mac, but I couldn't find anything about linux. Indeed, must be a DAW problem.

**Comment by TheWaveWarden** [comment]
Weird that this info is so hard to find - every time I get a case like this I spend ten minutes googling "Renoise VST3" and everything pops up but the desired information.

If you could confirm this happens with other VST3s as well (try [Surge](https://surge-synthesizer.github.io/) for a freakin' awesome synth) we could close this issue.

You also have the option to compile Odin as VST2 yourself, see compile instructions!

**Comment by TheWaveWarden** [comment]
Also note that Tracktion is closely related to JUCE - JUCE has had no VST3 support on linux until july I think. Maybe they haven't upgraded to the latest JUCE version in their stable release.
