### ISSUE TITLE
Bug ??? modmatrix assigned CC do not allow full range control of target

### ISSUE THREAD

**Issue by ulibs66** [TheWaveWarden/odin2#358]
Example: when I assign modwheel to filtercutofffreq. by midi learn I can control the cutoff from zero to max.
When assigning modwheel via modmatrix (amount 100%) I can only control a small range and not fully open the filter by modwheel.

**Comment by TheWaveWarden** [comment]
Hi @ulibs66,
This is for the same reason I explained in your other issue:
https://github.com/TheWaveWarden/odin2/issues/356

For exact values how much modulation affects the controls, please refer to the [manua](https://www.thewavewarden.com/assets/Odin2.2_manual.pdf) (in this case page 60).

You can always extend the range of the modulation by using multiple slots and insert the same source/destination combo. The next update 2.3.0 will also allow you to extend the amount of a single slot to 300%.
