### ISSUE TITLE
Osc and Filter stereo panning and possibility sync tempo in ChipTuneOsc's arpeggiator to DAW project tempo

### ISSUE THREAD

**Issue by MikieMike1983** [TheWaveWarden/odin2#361]
Hello, I like your synthesizer very much, you are doing a great job.

Some wishes for synth functionality.

As a composer and sound designer I really like to have control over Osc and Filter stereo panning and possibility to sync tempo in ChipTuneOsc's arpeggiator with DAW project tempo.

Thank you and best wishes!

**Comment by TheWaveWarden** [comment]
Hi Mike,

Please refer to [the manual](https://www.thewavewarden.com/assets/Odin2.2_manual.pdf) on page 7 for signal routing. You will notice that the routing before the amplifier is mono. Therefore, panning of individual oscs is not, and will not be possible.

The Chiptune Arpeggiator sync was requested often as well. The problem I see here is GUI spacing: Load a chiptune osc in **Osc Slot 2**. There's not much space left to put in a separate "sync" button I fear.

**Comment by TheWaveWarden** [comment]
Also for future issues, please keep two different requests in two separate issues to allow a distinguished discussion.
