### ISSUE TITLE
[Bug Report] MSE detects Odin2 as a virus

### ISSUE THREAD

**Issue by saucefrog** [TheWaveWarden/odin2#363]
**Describe the bug**
While downloading Odin2 on Windows 7 with Firefox, Microsoft Security Essentials detects it as a virus and deletes the downloaded installation file right away.

**To Reproduce**
1. Download Odin2 for Windows
2. See how MSE shows a notification and deletes the file

**Expected behavior**
Odin2 should not be a virus.

**Desktop (please complete the following information):**
 - Windows 7
 - Jeskola Buzz Machines
 - Odin Version 2.2.4
 - VST3

**Additional context**

**Comment by TheWaveWarden** [comment]
Hmmm that's a bummer. It is not a false positive, in case this is not clear. I just got into Kaspersky Allowlist program to prevent the same issue with Kaspersky. I'll have to see what I can do about this one.

Thanks for reporting!

**Comment by TheWaveWarden** [comment]
@saucefrog I just uploaded a version to the https://thewavewarden.com/odin2. According to VirusTotal, this should not trigger the WindowsDefender.

Can you confirm this?
