### ISSUE TITLE
[Bug Report] Legato Mode is clicky

### ISSUE THREAD

**Issue by mriga2019** [TheWaveWarden/odin2#366]
**Describe the bug**
when in legato mode the sound is clicking, even when env. are set wel
**To Reproduce**
1. Load synth plugin
2. Click on "legato mode"
3. Play note a legato line
4. clicking sound 

**Screenshots**

![image](https://user-images.githubusercontent.com/49905974/101012585-563ffa80-3563-11eb-8341-804bddcfe224.png)

**Desktop (please complete the following information):**
 - OS:  windows 10 pro
 - ableton 10
 - Odin 2.2.4
 - Plugin Format VST3

**Comment by TheWaveWarden** [comment]
Hi @mriga2019 

I can not reproduce this issue. Can you please provide a short audio sample? Perhaps it is better to change the waveform to sine as well - any clicks should be pretty apparent then.

One source of clicking that is still possible is the change in pitch from one note to the other: This is essentially a sudden change in the slope of the waveform, i.e. an edge. This should be very subtle though and can be circumvented with glide.

Your screenshot does not match the steps to reproduce - is this any particular setting?

**Comment by TheWaveWarden** [comment]
Upon further investigating your screenshot:

You have LFO1 routed to Filter1, but LFO1 is set to "Sync". Therefore, the LFO resets the waveform to the initial position on each note, which will produce a click because the filter cutoff-modulation is suddenly changed to zero before the waveform starts again.

Could this be the root of the problem?

**Comment by mriga2019** [comment]
Hey this could be the caseI will try this Weekend and if not Will Come with a video .It is a superb synth where for my gratitude Kind regardsManu Riga Bonzai progressive Sent from my Galaxy
-------- Original message --------From: TheWaveWarden <notifications@github.com> Date: 03/12/2020  21:22  (GMT+01:00) To: TheWaveWarden/odin2 <odin2@noreply.github.com> Cc: mriga2019 <manu.riga@telenet.be>, Mention <mention@noreply.github.com> Subject: Re: [TheWaveWarden/odin2] [Bug Report] Legato Mode is clicky (#366) 
Upon further investigating your screenshot:
You have LFO1 routed to Filter1, but LFO1 is set to "Sync". Therefore, the LFO resets the waveform to the initial position on each note, which will produce a click because the filter cutoff-modulation is suddenly changed to zero before the waveform starts again.
Could this be the root of the problem?

**Comment by TheWaveWarden** [comment]
Abandoned
