### ISSUE TITLE
Preset names not saved?

### ISSUE THREAD

**Issue by DCFOS** [TheWaveWarden/odin2#367]
I'm using Odin 2 on Reaper/Windows 10 and if I close the windows and comeback to it preset names are not saved.

EDIT : Sorry I'm dumb. There's actually no preset name displaying even. Guess this would go in feature request then?

**Comment by TheWaveWarden** [comment]
Yes, but the question is where to display them. This was actually a feature before the integrated patch-browser. The name was displayed in the area which is now occupied by the unison section. So the featuere is already implemented, no problem - but I don't see the space for it

**Comment by DCFOS** [comment]
> 
> 
> Yes, but the question is where to display them. This was actually a feature before the integrated patch-browser. The name was displayed in the area which is now occupied by the unison section. So the featuere is already implemented, no problem - but I don't see the space for it

Thanks for the answer.
Well, I don't have any idea how to actually assemble something like this, but if it's about finding any free space on the interface, there's one to the left of "reset synth", on top of the window.

**Comment by agung-wete** [comment]
how about below `Factory Presets`, in `Presets Library` menu ? Let say `User Presets` maybe

Also, how about make more easy to favorites patch ? Other synth has star next to patch name, click the star to favorite. And custom `favorites` folder to group all of them

**Comment by DCFOS** [comment]
> 
> 
> how about below `Factory Presets`, in `Presets Library` menu ? Let say `User Presets` maybe
> 
> Also, how about make more easy to favorites patch ? Other synth has star next to patch name, click the star to favorite. And custom `favorites` folder to group all of them

Totally agree on favorite, stars or any way...

**Comment by TheWaveWarden** [comment]
I'm just sorting through issues and this (retaining the highlighted name in the patch-browser after reopening the GUI) is not going to be any time soon.

Favouriting presets might be a thing, but thats another issue.
