### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by LeoKivi** [TheWaveWarden/odin2#368]
**Describe the bug**
I can't install the Odin2.exe due to a virus warning. 
How can i correct this ?

Best
Leokivi

**Comment by TheWaveWarden** [comment]
Hi LeoKivi,

What VirusEngine is detecting the installer? Rest assured that this is a false positive, see also the FAQ on my website.

Perhaps there is an option in you Virus protection which lets you install it anyway? Otherwise there's not much I can do.
