### ISSUE TITLE
WIN - Security warning from Norton

### ISSUE THREAD

**Issue by hlnorris** [TheWaveWarden/odin2#372]
Filename: odin2.tmp
Threat name: SONAR.Cryptlk.AF!g3Full Path: c:\users\harry\appdata\local\temp\is-grd7n.tmp\odin2.tmp

____________________________

____________________________

On computers as of 
Not Available

Last Used 
Not Available

Startup Item 
No

Launched 
Yes

SONAR Protection monitors for suspicious program activity on your computer.

____________________________

odin2.tmp Threat name: SONAR.Cryptlk.AF!g3
Locate

Unknown
It is unknown how many users in the Norton Community have used this file.

Unknown
This file release is currently not known.

High
This file risk is high.

____________________________

Source: External Media

____________________________

File Thumbprint - SHA:
Not available
File Thumbprint - MD5:
Not available

**Comment by TheWaveWarden** [comment]
Hi @hlnorris . This is a false positive, see the FAQ on my homepage.

Also, I assume you are using the latest version? The latest version seems to cause less problems than older ones.

Sadly, I cannot stay on top of every virus engine which randomly allerts every other week.
