### ISSUE TITLE
[Bug Report] Install fails on Windows 10

### ISSUE THREAD

**Issue by ujnhunter** [TheWaveWarden/odin2#374]
**Describe the bug**
During the installation of the .odin Preset files the installer appears to be creating .tmp files that it later tries to "rename" to the final .odin file, but Windows 10 is failing to allow this to happen, even when trying to install As Administrator. I've tried to copy the .tmp file elsewhere thinking it was a "location" or Directory issue, but the file itself seems to be "locked" and unable to be renamed.

**To Reproduce**
Run install file on Windows 10

![Odin2InstallError](https://user-images.githubusercontent.com/77746595/105223937-78e59d00-5b2a-11eb-8381-1b6e222a4eb8.png)

**Comment by TheWaveWarden** [comment]
Hi @ujnhunter 
Have you tried installing with the windows defender disabled?

**Comment by TheWaveWarden** [comment]
Abandoned
