### ISSUE TITLE
Please make it easier to build LV2 through scripts

### ISSUE THREAD

**Issue by alex-tee** [TheWaveWarden/odin2#375]
The build procedure for LV2 is way too complex and makes it hard to write a distro package. please include any submodules odin2 requires and put the logic in a Makefile or something. ideally you should be able to just run `make lv2` or something and get the plugin built

**Comment by KottV** [comment]
It would be easy without Projucer, but it's a requirement. And from my experience putting the generated Makefile in source is worth than re-generate it from .jucer each time.
Moving to cmake (JUCE 6 support it) will facilitate this issue.

You can see the automated build here: https://build.opensuse.org/package/view_file/home:kill_it:JUCE/odin2/odin2.spec?expand=1

https://build.opensuse.org/package/show/home:kill_it:JUCE/odin2

**Comment by KottV** [comment]
Actually this is possible to make:

Pull JUCE fork, build Projucer, re-generate Makefile, add LV2.mak, make, generate ttl.
IMHO switching to cmake is better way.

**Comment by magnetophon** [comment]
I have great experiences with cmake as well.

For inspiration, here is a PR that adds a cmake build to Bespoke Synth, another Juce project: https://github.com/BespokeSynth/BespokeSynth/pull/187

**Comment by baconpaul** [comment]
@TheWaveWarden if you want to move to cmake and wanna chat, hit me up. happy to lend some tips and pointers. done it a few times now :)

**Comment by baconpaul** [comment]
@TheWaveWarden I am just poking a little at odin this afternoon.

https://github.com/baconpaul/odin2/tree/general-upgrades

here's a branch which builds using cmake and submodules on my mac.

if you have a bit of time would be happy to polish this off for a merge. i want to try my clap adapters on another synth and it requires juce 6 and cmake! but if your schedule is still crammed i can just leave it sit there for a bit :)

**Comment by magnetophon** [comment]
@baconpaul Many thanks for this.
Unfortunately, I was not able to build it: 
https://sebsauvage.net/paste/?b72d9299e1e4a6af#zcemC04UA9h3Rn7jfrbGfNklpqmuNnoizCSYk6+hees=

Not sure what went wrong.

**Comment by baconpaul** [comment]
Well "I only built on macOS" is one thing that could have gone wrong :)

The `target_link_libraries` at the bottom has a bunch of PRIVATE stuff. Try changing that first PRIVATE to PUBLIC and seeing if it works? Wonder if linux resolves transient links to exes differently than macOS or some such? Those are all symbols from juce_core and stuff which is in the link list, but maybe needs to be public.

**Comment by magnetophon** [comment]
Thanks for the quick reply.
Not sure what you mean by "The target_link_libraries at the bottom".
I grepped the source for that string, and it came up combined with ``PRIVATE``in various places.

**Comment by baconpaul** [comment]
At the end of the cmake lists txt file is a section target link libraries that says odin 2 then private then a bunch of juce stuff then public then a small
List of juce stuff. Make the first one public and remove the second public and give it a whirl

**Comment by magnetophon** [comment]
Thanks, but no luck: https://sebsauvage.net/paste/?246f5445fe84456c#6msbH1KqzL71fWrAGZVMiUbwCrahyjCHJ+KbNKeMrU0=

**Comment by baconpaul** [comment]
oh well that's way way better
i'll have to boot linux and test it
but before I do that want to know if theres a desire to go this route. if so i can make it a mergable PR

**Comment by KottV** [comment]
@baconpaul 

works for me after adding
`
set_target_properties(Odin2_BinaryData PROPERTIES
    POSITION_INDEPENDENT_CODE TRUE)
`
at lines 1135

**Comment by magnetophon** [comment]
@KottV Could you be more precise?
When I do:
```
    sed -i '1135s/target_link_libraries(Odin2/set_target_properties(Odin2_BinaryData PROPERTIES POSITION_INDEPENDENT_CODE TRUE)/' CMakeLists.txt
```
I get: 
```
CMake Error at CMakeLists.txt:1137:
  Parse error.  Expected "(", got newline with text "

  ".
```

**Comment by KottV** [comment]
just put this line in the cmakelists.txt
your sed command contains extra parenthesis

**Comment by baconpaul** [comment]
Lemme take 5 minutes and update my branch - we don’t want random seds around.

**Comment by baconpaul** [comment]
OK my branch at ed02d06cfb5db8a118d291c00bd2e4cd6e262cde has both the all-public and the binary PIC in place.

**Comment by magnetophon** [comment]
Thanks!
Unfortunately, that branch still gives me an ld error: https://sebsauvage.net/paste/?96fe9819f6b22291#l1KC27XVphAXh5pSzOZU4B0hiR4yoU4PS/PFy6vWtkE=

**Comment by baconpaul** [comment]
right
well then i would need to boot linux and windows and run it round the horn
before i do that i want to hear from @TheWaveWarden to see if there's even interest in that!
happy to do it and get it working and stuff
but you know. want to make sure that's desired first!

**Comment by baconpaul** [comment]
(As opposed to them doing the conversion themselves that is. Don't want to intrude :) )

**Comment by TheWaveWarden** [comment]
@baconpaul sorry for the late answer. Yes, CMake support seems like a great addition. I would need to make adapt the Azure pipelines and make sure everything works as before. I cannot guarantee this will happen immediately, but should be doable in a reasonable timeframe. Happy to receive the PR.

In relation to the original topic of this issue: I guess so far there's no LV2 builds on Linux involved?

**Comment by KottV** [comment]
> Thanks! Unfortunately, that branch still gives me an ld error: https://sebsauvage.net/paste/?96fe9819f6b22291#l1KC27XVphAXh5pSzOZU4B0hiR4yoU4PS/PFy6vWtkE=

looks like nixos does something weird with cmake paths during build

**Comment by magnetophon** [comment]
In case any other nix users want to give it a go, here's the pkg I used:
```nix
{ stdenv

, lib
, fetchFromGitHub
, cmake
, pkg-config
, alsa-lib
, freetype
, libjack2
, lv2
, libX11
, libXcursor
, libXext
, libXinerama
, libXrandr
, libGL
}:

stdenv.mkDerivation rec {
  pname = "odin2";
  version = "unstable-2022-02-23";

  src = fetchFromGitHub {
    owner = "baconpaul";
    repo = "odin2";
    rev = "ed02d06cfb5db8a118d291c00bd2e4cd6e262cde";
    fetchSubmodules = true;
    sha256 = "sha256-VkZ+mqCmqWQafdN0nQxJdPxbiaZ37/0jOhLvVbnGLvQ=";
  };

  nativeBuildInputs = [
    cmake
    pkg-config
  ];

  buildInputs = [
    alsa-lib
    freetype
    libjack2
    lv2
    libX11
    libXcursor
    libXext
    libXinerama
    libXrandr
    libGL
  ];

  # cmakeFlags = [
  # "-DJUCE_SUPPORTS_LV2=ON"
  # "-DSURGE_JUCE_PATH=${juce-lv2}"
  # ];

  # JUCE dlopen's these at runtime, crashes without them
  NIX_LDFLAGS = (toString [
    "-lX11"
    "-lXext"
    "-lXcursor"
    "-lXinerama"
    "-lXrandr"
  ]);

  # see https://github.com/NixOS/nixpkgs/pull/149487#issuecomment-991747333
  # export XDG_DOCUMENTS_DIR=$(mktemp -d)
  # postPatch = ''
  # sed -i '1135s/target_link_libraries(Odin2/set_target_properties(Odin2_BinaryData PROPERTIES POSITION_INDEPENDENT_CODE TRUE)/' CMakeLists.txt
  # cat  CMakeLists.txt
  # '';

  # sed -i '1136s/PRIVATE/PUBLIC/' CMakeLists.txt
  # sed -i '1153s/PUBLIC//' CMakeLists.txt
  #
  meta = with lib; {
    description = "Odin 2 Synthesizer Plugin";
    homepage = "https://thewavewarden.com/odin2";
    license = licenses.gpl3;
    # platforms = [ "x86_64-linux" ];
    maintainers = with maintainers; [ magnetophon ];
  };
}
```

**Comment by baconpaul** [comment]
I set some time aside this week to try in Mac win and lin and clean this up and modify azure and get a pr together

**Comment by baconpaul** [comment]
I finally got around to pushing a cmake branch here as a pull request 

@TheWaveWarden if you want I can also fix the azure pipelines to use cmake rather than projucer and remove the jucer file? But if you pull my pr and submodule update it should work

for lv2 in the fork I would need to make juce repointable like I did for surge but wirh juce7 coming with lv2 support perhaps a better strategy is just to move to j7 as a submodule and be consistent all platforms?

**Comment by dromer** [comment]
@baconpaul I was going to suggest the same. Having consistent builds (and formats) for all platforms would be nice! (the LV2 builds are currently only on Linux, which is odd for a cross-platform format ;) )

**Comment by TheWaveWarden** [comment]
@dromer Ah, I didn't even know LV2 was cross platform. Are people using it on Windows though?

Anyways, if important I'd suggest opening a new issue. This one is solved with the recent switch to CMake.

**Comment by dromer** [comment]
@TheWaveWarden this is one of the biggest misconceptions. LV2 works on all major operating systems and then some. It's just a plugin format, nothing tying it to Linux in any way. Current support in Reaper, Ardour, Mixbus, Carla, Zrythm, Mixxx, etc.
