### ISSUE TITLE
[Bug Report] - Odin2 does not appear in ProTools 2020.5

### ISSUE THREAD

**Issue by winglessveritas** [TheWaveWarden/odin2#377]
**Describe the bug**
Odin 2 Synth not appearing in ProTools 2020.5

**To Reproduce**
1. Install Odin2.exe
2. Follow Prompts to Install Odin2 in existing VST folder
3. Launch ProTools
4. Create New Instrument Track
5. Inserts do not show Odin2 in the list, though other VST's are present.  
6. Confirm Odin2 exists in VST folder
7. Repeat steps 1-6

**Expected behavior**
Odin 2 Synth Should be present in inserts for instruments (or perhaps "other"), like other synths.  Instead, it doesn't appear in any category.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Pro Tools 2020.5
 - Odin Version 2
 - Plugin Format VST3

**Additional context**
I reinstalled according to the FAQ but it still doesn't show up in ProTools.

**Comment by TheWaveWarden** [comment]
@winglessveritas 
I might be mistaken, but Pro Tools does not support VST3? You say it doesn't show besides the other VSTs you have installed? Are you sure these others are not AAX plugins?

**Comment by TheWaveWarden** [comment]
Abandoned by author
