### ISSUE TITLE
.git/objects huge pack, 779 MB

### ISSUE THREAD

**Issue by KottV** [TheWaveWarden/odin2#378]
Hi,

Just wonder, is possible to clean git cache (or what is it) to reduce the size of objects?

**Comment by TheWaveWarden** [comment]
I think it is binary data, foremost wavetabledata, which changed a lot during development and got checked in every time. Other than that its probably graphics, which also changed multiple times.

I already slimmed this from 3GB I think to what it is now when migrating from gitlab to github. 

Can you slim it locally? I tried using git-filter-branch and BFG back then, but ended up with a broken timeline.

**Comment by KottV** [comment]
Yeah, I've tried to strip .pack with BFG too, but without success.

**Comment by TheWaveWarden** [comment]
I guess its huge file size vs. broken history then ;-)

How does it affect you?

**Comment by KottV** [comment]
I used to run:
java -jar ~/bin/bfg.jar --strip-blobs-bigger-than 2M odin2

and it stripped just to 653 MB
maybe try to select smaller size? History looks not brocken for me.
[history.new.gz](https://github.com/TheWaveWarden/odin2/files/5940347/history.new.gz)

**Comment by KottV** [comment]
I'm afraid it's hard to do something with that. So let's close it, if you don't mind.
