### ISSUE TITLE
Dear programmers , the preset file, though installed in the right place,  is not a VSTPRESET file. SO, Cubase is not able to show  the names in the Inspector.

### ISSUE THREAD

**Issue by Larenzo2012** [TheWaveWarden/odin2#380]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Larenzo2012** [comment]
Very newbe here, sorry if i do things in a perculiar way. But i think ODIN2 is a GREAT SYNTH and deserves to fit in smoothly in any DAW. This means the presets , factory and user , have to show up in the way the DAW handlls presets. In case of Cubase (Pro10.5) the preset names are supposed to show in the inspector. In this way one can navigate the presets with up and down arrow.  Good luck and succes

**Comment by TheWaveWarden** [comment]
@Larenzo2012 I am not familiar with VSTPreset files. I can imagine this is a native format provided by Steinberg, since they also provide the API for VSTs. I've never seen this file format being used anywhere else, and I want to avoid catering to one special DAW (with the exception of major bugs of course).

**Comment by Larenzo2012** [comment]
Hi Wavewarden
Thnx for your swift reply.
Yes i understand about “ catering for one daw”.
However, i use plugins, both paid and free, from various designers, that use this file for their presets.
Shall i send you an example of a free VSTi
that uses this file? Or can i help you
otherwise so you can think about the VSTPRESET file for ODIN2?
Kind regards , Lars Weeling

Any project? Save, save, save


Op 24 feb. 2021 om 10:28 heeft TheWaveWarden <notifications@github.com> het volgende geschreven:

﻿

@Larenzo2012<https://github.com/Larenzo2012> I am not familiar with VSTPreset files. I can imagine this is a native format provided by Steinberg, since they also provide the API for VSTs. I've never seen this file format being used anywhere else, and I want to avoid catering to one special DAW (with the exception of major bugs of course).
