### ISSUE TITLE
[Feature Request] Make paths to soundbanks configurable

### ISSUE THREAD

**Issue by m-camilleri** [TheWaveWarden/odin2#382]
It would be nice to allow users to configure the paths to the presets and user soundbanks.

**Comment by TheWaveWarden** [comment]
@m-camilleri I am just now working on a bigger change regarding soundbank location, see
https://github.com/TheWaveWarden/odin2/issues/322

I am unlikely to bring in yet another change for the time being. But I can tell you the codelines for the location, so you can compile a version which looks for presets wherever you fancy ;-)
