### ISSUE TITLE
[Bug Report] JUCE doesn't install include_juce_audio_plugin_client_LV2.cpp

### ISSUE THREAD

**Issue by yurivict** [TheWaveWarden/odin2#383]
**Describe the bug**

The file ```include_juce_audio_plugin_client_LV2.cpp``` is mentioned here https://github.com/TheWaveWarden/odin2/blob/master/LV2.mak#L15 but juce-6.0.8 doesn't install it.

**To Reproduce**
1. Projucer --resave Odin.jucer
2. echo "include ../../LV2.mak" >> Builds/LinuxMakefile/Makefile
3. cd Builds/LinuxMakefile
4. gmake

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.2
 - Odin Version 2.2.3.beta
 - Plugin Format LV2

**Comment by TheWaveWarden** [comment]
Hi @yurivict are you using the custom JUCE branch mentioned in the readme in section "Building LV2"?

**Comment by yurivict** [comment]
No. I didn't realize I have to use the custom branch. If this is a requirement then I can't build odin2 because on FreeBSD JUCE required some patching that is done in the port.

**Comment by TheWaveWarden** [comment]
Ok, maybe you can work it out. JUCE by default supports no LV2, it is the custom fork referenced in the readme, which does it. Although admitedly I understand very little of what it does.
