### ISSUE TITLE
[Bug Report] UI size broken in Renoise

### ISSUE THREAD

**Issue by jnurmine** [TheWaveWarden/odin2#385]
**Describe the bug**
The UI size is wrong when re-opening the plugin.

**To Reproduce**
Steps to reproduce the behavior (in Renoise):
1. Load synth plugin
2. Click Editor. UI is OK.
3. Close synth plugin window.
4. Click Editor. UI re-appears very small.

**Expected behavior**
UI size should persist.

**Screenshots**

After step 4:

![image](https://user-images.githubusercontent.com/221556/123153912-83ec8280-d466-11eb-842e-0a225865e14c.png)

At step 4, Renoise writes out:
```
Renoise LOG> Vst3Window: Plugin requested new Windowsize 1200, 921
Renoise LOG> Vst3Window: Plugin window attached via _XEMBED_INFO
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - DAW and version being used: Renoise 3.3.2
 - Odin Version: 2.2.4
 - Plugin Format: VST3

**Additional context**
I am not sure if this is a problem with Renoise or Odin2. Renoise seems to think it's drawing 1200x921. I don't recall seeing this issue with other plugins.

**Comment by TheWaveWarden** [comment]
Hi @jnurmine 

Recent changes were made to disable window resizing by dragging, which might have implications for this as well.
Could you please install the Odin 2.3 preview version found here:

https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel

And report whether the problem ist still existent?

**Comment by jnurmine** [comment]
Hi @TheWaveWarden,

thanks, I tried the Odin 2.3 preview -- unfortunately, the problem still exists.

**Comment by jnurmine** [comment]
FYI this works much better on Renoise 3.4.0. The UI doesn't cram to a very small box.
