### ISSUE TITLE
[Bug Report] Tuning button is missing (can't load tunings.)

### ISSUE THREAD

**Issue by LiftPizzas** [TheWaveWarden/odin2#386]
The tuning button is not visible. I tried clicking around the area (in case it's there but transparent), changing 100/150%, restarting reaper, rebooting windows, etc.

I'm using 2.2.4 that I downloaded from the website. This is the first time I had heard of the software so no prior versions have been installed here.

**Screenshots**
![odinbuttonmissing](https://user-images.githubusercontent.com/20491378/124339236-bb4be500-db72-11eb-96f6-6f47f8d73ac5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Reaper v6.29
 - Odin 2.2.4 64 bit
 - Plugin Format vst3i

**Additional context**
I also have Visual Studio 2019 and the 2022 preview installed. (Perhaps one of my runtimes is newer/older?)

**Comment by TheWaveWarden** [comment]
HI @LiftPizzas 
Tuning is a feature of the upcoming version Odin 2.3, which is currently in public beta. The website still ships 2.2.4, which does not have this feature.

You can find the installer for the 2.3 beta here:
https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel
