### ISSUE TITLE
[Bug Report] I believe the .deb package on website needs rebuild after commit bc2388a

### ISSUE THREAD

**Issue by basschaser** [TheWaveWarden/odin2#387]
Hi, this is the former @ryyzerr, maintainer of the AUR package for this project. I am about to create a binary version of the package using the .deb package from your website. However, it appears to carry a bug (I suspect) from a while ago, where Ardour doesn't recognize the LV2 plugin correctly as an instrument, due to having inputs assigned to it. This was fixed in commit bc2388a, in azure-pipelines.yml

1. Install plugin from .deb package on website
2. Open Ardour
3. Add new track, and try to select instrument plugin - it does not display Odin2 as a choice

Expected behavior:
When selecting an instrument for the new track, Odin2 should be an option.
When using my compiled AUR package, it works as expected. When using the binary .deb package, it does not.

To fix:
I believe the .deb package on the website simply needs to be rebuilt from a recently compiled version of Odin2. I have a checksum for that file from before commit bc2388a, and it has not changed since then.

System Info:
 - OS: Linux
 - DAW: Ardour 6.7.0
 - Odin Version: 2.2.4
 - Plugin Format: LV2

**Comment by TheWaveWarden** [comment]
This commit is on the devel branch - it is currently undergoing testing soon to be merged onto master with version Odin 2.3. However before that I will not change the .deb on my website, as said commit is amidst development and surely contains half finished features.

Meanwhile, you can pack against the 2.3 beta version on the NightlyDevel page.
https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel

It is pretty stable at this point, I'm only waiting for JUCE to be updated to the next version, which will fix a minor bug and mark the release of 2.3.

Please also keep in mind that 2.3 uses the new location for user presets in `~/.local/share/odin2`.

**Comment by basschaser** [comment]
Thanks for the info.

I will await the stable 2.3 release then, and in the meantime I will have ready a solution to handle the user presets migration.
