### ISSUE TITLE
[Bug Report] Unison Engine use High CPU Usage when set to >3 while turning on Distortion and Long Release

### ISSUE THREAD

**Issue by sandycorzeta** [TheWaveWarden/odin2#392]
**Describe the bug**
So, i tried to make a simple trance pluck patch that use >3 unison and detuning, with slightly long release and short filter. Everything is fine, until i turned on the Distortion it raise the CPU high and make stutter.

**To Reproduce**
1. Load Synth
2. Init the Plugin
3. Follow the video

**Video**
https://user-images.githubusercontent.com/4186454/130768741-c1ee62db-1dfe-4c5f-899b-b2d1d269ac42.mp4
*forgive me if its bitcrushing the audio, this is because the audio codec of bandicam that i used

**Expected behavior**
This shouldn't happen, and not spiking the CPU. I've tried it on different commercial VST like Sylenth or even free one like Helm, they didn't have this problem. Even when i ramp up the Amp Release fader or rising the Unison/voice. Perhaps the release algorithm or the Unison engine isn't optimized or maybe the Distortion one causing the problem. I'm also on 2048 buffer rate which is should be fine and not taxing the CPU much. I'm using an older device too, an A6-6310 processor.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC
 - DAW and version being used [REAPER 6.34]
 - Odin Version [2.3.1]
 - Plugin Format [VST 3]

**Comment by sandycorzeta** [comment]
Funnily enough, even i just playing with Amp Release and Unison also give the hiccup when i turned on the Distortion.
For a Release that is <1s only managed it to use 3 unison. When going up to 4, the VST start to tank my CPU.
Same goes when i crank up the Release to >1s, i only got 2 unison only before it start making a stutter when the Distortion turned on.

Everything seems fine when the distortion is turned off, even when i crank up the Amp Release up all the way to 10s

https://user-images.githubusercontent.com/4186454/130771629-6f683fd0-1e09-48e3-b9e5-dae0af286bb9.mp4

**Comment by TheWaveWarden** [comment]
HI @sandycorzeta,
I've explained this to great lengths in various forums and forms around the internet:

When using unison **you are triggering multiple voices at the same time**. When using long release, which blend into the next notes, you will use even more voices. Using 10 voices means 10 times the processing.

Furthermore, the distortion internally uses 3x oversampling in each voice. This is for technical reasons, to prevent aliasing. It is, however not easy on your CPU. From your demo We can hear that you use chords with three notes, combined with blending release lengths and 4x unison, makes for 24 voices being played simultaneously (which coincidentally is the voice limit of the synth). The situation is not ideal, but it's not a bug either.
