### ISSUE TITLE
[Feature Request] VST 2.4 (but $teinberg stupid licensing rules, Native Instruments)

### ISSUE THREAD

**Issue by DomiKamu** [TheWaveWarden/odin2#394]
**Is your feature request related to a problem? Please describe.**
Frustrated because no VST 2.4 (only VST3), by the way, it's not usable from Komplete Kontrol app/plugin, too bad, and thank you $teinberg and NI.

**Comment by TheWaveWarden** [comment]
Hi @DomiKamu 

I take it you already know about the licencing situation by Steinberg? You will find various information around the web regarding it. I am just as helpless/frustrated as you are here.

You still have the option to compile the synth yourself as a VST2 - just follow the instructions on the mainpage (and expect to search google for 30 mins until you will find the VST2-SDK). If you're new to this I am happy to assist along the way.

Other than that someone else might have published a (probably outdated) VST2 version somewhere on the internet.
