### ISSUE TITLE
Installed Odin II on Mac OS, and the VST is nowhere to be found

### ISSUE THREAD

**Issue by Cwyoming** [TheWaveWarden/odin2#396]
I have downloaded Odin II. I have installed it. But I cannot find it anywhere in my computer. It says install complete. And I can find the Installer. And Ive now re-installed it several times. But the VST itself isn’t showing up anywhere. Any insight as to what Im doing wrong.

Oh its for Mac OS btw. Powerbook. I run Reason version 10, for all of my softsynths and it just won’t show up there

Thank you 
cody

**Comment by TheWaveWarden** [comment]
Hi Cody,

You're trying to run a VST3 plugin, but Reason is one of the last hosts to only support VST2. Your options now are:
- Compile the VST2 version yourself. Instructions are on the main page of this repo (I am legally not allowed to distribute the VST2, courtesy Steinberg Media Technologies)
- Reason Studios have announced in their [road map for Reason](https://www.reasonstudios.com/blog/roadmap-for-reason), that Reason 12 will have VST3 support come **february 2022**. So you'd have to wait and then upgrade
- use a different DAW
