### ISSUE TITLE
[Feature Request] Modulate LFO influence

### ISSUE THREAD

**Issue by unfa** [TheWaveWarden/odin2#398]
I've been making a brass patch and wanted to implement the "growl" at the note start. Gordon Rein in his Synth Secrets recommends using a quickly modulated filter cutoff (like Filter FM) fro that. The problem is - in Odin2 there is no way to modulate LFO modulation amount.

There isn't even a way to automate modulation influence.

I think there are two solutions:

1. Allow assign modulations that control amount of other modulations in the Mod Matrix (more flexible, more difficult)
2. Add an "amount" parameter to LFOs that can be modulated to make things like variable vibrato or filter growls like what I mentioned above possible.

I ended up using another oscillator and synth pair to make the grown and cross-fade between that and the original oscillator/filter pair to achieve the effect. it works, but it's far from ideal.

Also exposing modulation matrix amounts as plug-in's automatable parameters an enabling them for MIDI learn would be great to expand this functionality.

**Comment by unfa** [comment]
Here's the patch in question if anybody's curious. Consider it CC-0.
[Growly Brass.odin.zip](https://github.com/TheWaveWarden/odin2/files/7178875/Growly.Brass.odin.zip)

**Comment by TheWaveWarden** [comment]
Hi @unfa 

>     1. Allow assign modulations that control amount of other modulations in the Mod Matrix (more flexible, more difficult)

More difficult, yet already implemented ;-) In the modmatrix the rightmost collumn labeled "Scale" is reserved for that. See also sections 7.1 and 7.2 in [the manual](https://www.thewavewarden.com/assets/Odin2_manual_v2.3.0.pdf).

Or did I miss your point?

**Comment by unfa** [comment]
Ah, but it seems the Scale is not modulatable nor automatable ot is the Manual out of date on this?
![Uploading image.png…]()

**Comment by TheWaveWarden** [comment]
@unfa The manual is up to date. You can set this up to be "automatable": 

For example scale your modulation by the ModWheel, then record Modwheel automation in your host. Now the modulation is controlled by the automation data in your host.

If you want to have modulation on note-start only, like you described in your OP I suggest using a dedicated ADSR with a short decay and scaling by that.

Making the controls in the ModMatrix automatable or modulatable themselves would introduce a third layer of scaling. I don't quite remember why the amount-controls aren't audio-parameters (i.e. automatable), but there's probably some reason for that.

Does this solve your problem? :-)

**Comment by unfa** [comment]
Ah, this seems like a solution I could use. I also should figure out using an Envelope to modulate an LFO influence, since that seems to be doable with the Mod Matrix...
