### ISSUE TITLE
[Bug Report] Crackling audio when using multiple instances of Odin 2 (Windows FL Studio)

### ISSUE THREAD

**Issue by KesshiDesu** [TheWaveWarden/odin2#400]
**Describe the bug**
When using multiple instances of Odin 2, if more than one instance has reverb enabled, it affects all the other instances by adding crackling audio noise. The noise increases as you add more instances with reverb.

**To Reproduce**
1. Load synth plugin
2. Enable Reverb
3. Load another instance of the synth
4. Enable Reverb
5. Both instances now have noise (even when only one of them is played)
6. Add more instances to hear more noise being added

**Expected behavior**
There should be no crackling noise.

**Screenshots**
Here is a video demonstrating:
https://user-images.githubusercontent.com/46252567/134607708-f68e54d9-3789-4bd1-9965-eb154c2da7b2.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DAW and version being used: FL Studio v20.8.4
 - Odin Version: 2.3.1
 - Plugin Format: VST3

**Additional context**

**Comment by KesshiDesu** [comment]
Github seems to be muting the audio on the video but if you download the video, the sound is there.

**Comment by TheWaveWarden** [comment]
Hi @KesshiDesu 

I can't hear audio on the video, even after downloading.

On my Linux machine I can't reproduce the behaviour you're describing, but I will test on my windows machine later. Meanwhile, are you sure you're not running into performance issues? Crackling sound is often an indicator for your CPU being overtasked.

**Comment by KesshiDesu** [comment]
I'm running a Ryzen 7 3800x and the cpu usage is around 10%. The artifacting doesn't sound like a cpu issue.

I think I fixed the audio on the video, the issue can be heard clearly 23 seconds into the video

https://user-images.githubusercontent.com/46252567/134662849-3986efc6-eaa0-42e5-aced-6de3b08f683e.mp4

**Comment by TheWaveWarden** [comment]
Ah yeah, now it works!

Ok, that doesn't sound right. Can be seen in the spectrum meter on top as well. I will take a look at this, thanks for reporting.

I wonder if it might have something to do with the "Clone" command you're using to instantiate the second instance. Anyway I'll have to test!

**Comment by KesshiDesu** [comment]
The same effect happens if I create new instances normally (without using the clone)

**Comment by TheWaveWarden** [comment]
@KesshiDesu I'm fairly certain I fixed the issue. There was static data in the reverb class, that was shared between instances. Annoys the hell out of me, since thousands of people downloaded this version...

Can you download the nightly build from here and confirm it works for you?
https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel

I'll put this version on my homepage tommorow.

**Comment by KesshiDesu** [comment]
I can confirm the issue is fixed on the nightly build.
Thanks for the quick response and fix, I've really been enjoying using Odin 2

**Comment by TheWaveWarden** [comment]
Awesome! Thanks for reporting and testing!
