### ISSUE TITLE
Install onto Windows10 impossible, if root device is not C:

### ISSUE THREAD

**Issue by pohlw** [TheWaveWarden/odin2#408]
**Describe the bug**
Installer fails onto Windows10, if root device is not C:

**To Reproduce**
1. Have a windows with a root device other than C: (rare but not impossible)
2. try running the latest odin2 installer; note that it's impossible to change any file locations
3. the installer fails  (message like "cannot write into ...programdata")

**Expected behavior**
Either let the user define the locations for installing or (preferrably)
determine the current windows root device (which can be other than "C:")

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/42252664/161422961-81ed52a5-1837-4925-8ea8-4a6d3f9535f4.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 latest update
 - DAW all 
 - Odin Version 2.3.2
 - Plugin Format [VST3]

**Additional context**
Windows 10 with root device not  "C:"

**Comment by TheWaveWarden** [comment]
@pohlw I didn't even know that was possible lol. Are you able to work around it by creating said folder, or do you have not C: at all?

I currently don't have the time to tend to this, and it seems a rather niche problem. We can leave this issue open of course. If you don't find another solution, I can hack you an installer which installs to another drive.

The reasoning behing not being able to choose locations was originally intended for VST3, as the standard dictates the location to be on C: and some hosts will not allow for another location whatsoever. So I figured I'd spare myself the "host can't find plugin" emails. I never imagined the config files etc. to be the problem though.

Now that I think of it, even when fixing the installer some stuff inside the plugin is hardwired to C:, so you won't be able to use the preset library and everything that is stored in the config file (GUI size etc.)

**Comment by pohlw** [comment]
Why don't you evaluate the global environment variables "ProgramData" 
and "SystemDrive" which should always point to the correct location both 
at installtime and runtime (presets, config)?

You're correct: hardwiring should be eliminated both for install and 
runtime...


Am 03.04.2022 um 22:40 schrieb TheWaveWarden:

**Comment by TheWaveWarden** [comment]
Like I said, because I don't have time. Now that I think of it, runtime might actually handle it, becuase Odin is using the [special paths provided by JUCE](https://docs.juce.com/master/classFile.html#a3e19cafabb03c5838160263a6e76313d) .

If you find a solution, I'm happy to merge onto master. The iss installer is somewhere in `installers/windows/`. It's a rather small file.

**Comment by pohlw** [comment]
Here is a solution:

-----------Patch odin2-master/installers/windows/infobefore.txt

2c2
< C:\Program Files\Common Files\VST3\Odin2.vst3
---
 > <systemdrive>:\Program Files\Common Files\VST3\Odin2.vst3
5c5
< C:\ProgramData\odin2
\ No newline at end of file
---
 > <systemdrive>:\ProgramData\odin2
\ No newline at end of file

-----------Patch odin2-master/installers/windows/win_installer.iss

17,18c17,18
< Name: "C:\ProgramData\odin2\Soundbanks"; Permissions: everyone-full
< Name: "C:\ProgramData\odin2\Soundbanks\User Patches"; Permissions: 
everyone-full
---
 > Name: "{commonappdata}\odin2\Soundbanks"; Permissions: everyone-full
 > Name: "{commonappdata}\odin2\Soundbanks\User Patches"; Permissions: 
everyone-full

Worked for me.


Am 03.04.2022 um 23:30 schrieb TheWaveWarden:

**Comment by TheWaveWarden** [comment]
I've added you suggestion for Version 2.3.3. Thank you!
