### ISSUE TITLE
Update Source Code installation procedure

### ISSUE THREAD

**Issue by Xeno-Idaltu** [TheWaveWarden/odin2#410]
The instructions are outdated. I followed all the steps and still was unable to build Odin2 (Version-2.3.2)

On build, the output is:
error: 'showMessageBox' is not a member of 'juce::AlertWindow'

I used the latest Juce and JuceLV2 because it kept giving out errors. I was able to build Odin2 (Version-2.3.1) as an Standalone and LV2 but the LV2 version doesn't use effects properly, hence why I want to build Odin2(V-2.3.2)

The main reason I'm building from Source Code is because it crashes on LMMS via Carla. I found a post telling us to edit /Source/gui/Knob.h to change "knob" to "knov".
This tweak works and makes it possible to use Odin2 on LMMS but many effects are not responsive.

 - OS: [Ubuntu-21.10]
 - LMMS-1.3.1-Alpha
 - Odin Version [2.3.2]
 - Plugin Format [LV2]

**Comment by gitterdude** [comment]
If you're using JUCE 6.1.6 you can use the current, as of March 30, version of JUCELV2. It's commit 58b303e24967

**Comment by TheWaveWarden** [comment]
Hi @gitterdude. Sorry for the late response and thanks for reporting. For version 2.3.3 we have:

- added JUCE as a git submodule and switched to cmake, which mitigates all "wrong JUCE version" kinda errors
- renamed `Knob` to `OdinKnob`. (The proper solution would be to wrap the codebase in `namespace tww` though)
