### ISSUE TITLE
[Bug Report] I have the same error code and it doesnt look like this thread answered the problem. Does anyone know the fix? : "Note that the following files appear to be plugin files, but failed to load correctly"

### ISSUE THREAD

**Issue by Nick-H123** [TheWaveWarden/odin2#411]
**Describe the bug**

**To Reproduce**
1. Load synth plugin
2. Click on '...'
3. Play note C3
4. See Error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - DAW and version being used [e.g Bitwig 3.2.4]
 - Odin Version [e.g. 2.2.4]
 - Plugin Format [VST3 / AU / LV2]

**Additional context**

**Comment by TheWaveWarden** [comment]
Hi @Nick-H123 

This is not much to go by. You put some error code in the title along with some text and omit all of the interesting information which was asked for in the body.

Please open a clean issue which has a clear title and provides the information asked for.
