### ISSUE TITLE
Rename a Preset Bank selecting the wrong Bank via right click

### ISSUE THREAD

**Issue by cxbignekoc** [TheWaveWarden/odin2#413]
**Describe the bug**
When click on a New Bank the Option RENAME selects the Bank above the selected one.

**To Reproduce**
1. Load synth plugin
2. Click on 'Preset Library', First Column select NEW, give Name and Enter, change mind and right click for RENAME
3. See the wrong Bank is selected

**Expected behavior**
i expected that i can rename the selected bank, not the above one

**Screenshots**
(https://www.screencast.com/t/z8yo9fAfa)

**Desktop**
 - OS: [Windows 10]
 - DAW and version being used [Bitwig 4.0.7]
 - Odin Version [2.3.2]
 - Plugin Format [VST3]

**Additional context**
deleting works for the selected one

**Comment by TheWaveWarden** [comment]
Hi @cxbignekoc . Sorry for the late response and thanks for reporting this issue. 

I fixed the issue for the upcoming 2.3.3 release.
