### ISSUE TITLE
[Bug Report] Blurry text and UI when setting windows scaling to above 100%

### ISSUE THREAD

**Issue by KesshiDesu** [TheWaveWarden/odin2#418]
**Describe the bug**
Blurry text and UI when setting windows scaling to above 100%

**To Reproduce**
1. Change windows scaling to anything above 100%
2. Load synth plugin

**Expected behavior**
The text and UI should stay clear 

**Screenshots**
This is with 125% scaling
![image](https://user-images.githubusercontent.com/46252567/170150905-cb0f4c9f-df1c-480f-90c1-cc5ed19e8a91.png)
The issue is not there with 100% scaling
![image](https://user-images.githubusercontent.com/46252567/170150971-5e578d16-932f-449a-9ec8-a331ff93b1d6.png)
I tested and it is not affected by my DAW's scaling settings

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DAW and version being used FL Studio v20.9.1
 - Odin Version: 2.3.2
 - Plugin Format [VST3 / AU / LV2]

**Additional context**
I upgraded to a 1440p monitor and use 125% scaling so that things aren't too small. The blurriness on the plugin is quite distracting to me so I'd appreciate a fix

**Comment by TheWaveWarden** [comment]
Hi @KesshiDesu. Sorry for the late answer. Can you install the latest build from here

https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel

and see if it fixes the issue? You can still expect some blurryness, but not the "nearest neightbour" interpolation seen in your first screenshot.

**Comment by KesshiDesu** [comment]
The blurriness is much better now, it's much less distracting. Using windows scaling is not as clear as the plugin's scaling but at 125% windows scaling I'm happy with it. Thanks for the fix!

**Comment by TheWaveWarden** [comment]
Great!
