### ISSUE TITLE
[Bug Report] no 2.3.2 tag

### ISSUE THREAD

**Issue by hfiguiere** [TheWaveWarden/odin2#425]
**Describe the bug**
There is a 2.3.2 release to download, but no 2.3.2 tag in git, making it impossible without guess work to build 2.3.2

**To Reproduce**
1. Go to https://github.com/TheWaveWarden/odin2/tags
2. There is no 2.3.2
3. Go to https://thewavewarden.com/odin2
4. There are 2.3.2 binaries

**Expected behavior**
A 2.3.2 tag.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**

**Comment by TheWaveWarden** [comment]
I've pushed tag `v2.3.2`

**Comment by hfiguiere** [comment]
thanks!
