### ISSUE TITLE
[Bug Report] AU version fails to validate in logic, shows white UI in hostingAU

### ISSUE THREAD

**Issue by TheWaveWarden** [TheWaveWarden/odin2#428]
Bug was reported [here](https://www.kvraudio.com/forum/viewtopic.php?p=8451436#p8451436) originally.

**Describe the bug**
With the latest installer from the [NightlyDevel Release page](https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel), Odin 2 fails to validate in Logic. Shows up with a white UI in hostingAU.

**Desktop**
 - OS: mojave (10.14.6)
 - DAW: logicX 10.5.1
 - Odin Version 2.3.3
 - Plugin Format AU

Whether the problem exists with other plugin formats is not clear.

Logic validation error:
```
 validating Audio Unit Odin2 by TheWaveWarden:

    AU Validation Tool
    Version: 1.6.1a1 
    Copyright 2003-2013, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'ODIN' - 'WAWA'
--------------------------------------------------
Manufacturer String: TheWaveWarden
AudioUnit Name: Odin2
Component Version: 2.3.3 (0x20303)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF


validation result: couldn’t be opened
```

@baconpaul

**Comment by baconpaul** [comment]
Right so on my mac (OSX 12 and LPX 10.7.4) it all works

And that's the thing that solves it. 

When we ported to CMake I didn't add an OSX Minium Version. The GitHub builds build on 10.15 so your binary won't work on 10.14.

At the very very top of your CMake file you want to add

```
set(CMAKE_OSX_DEPLOYMENT_TARGET 10.13 CACHE STRING "Minimum macOS version")
```

this has to happen *before* your PROJECT. (You may even be able to survive back to 10.11 - surge can)

then do a rebuild and voila i bet it will work for this user.

Sorry I forgot that. I should have seen it when I submitted the cmake PR :(
