### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by PietrareanuAndrei** [TheWaveWarden/odin2#437]
I am using Ableton Live 10.1 and supports vst3, but when the plugin is installed it only generates a .vst3 file which my DAW didn't recognize. All my plugins (that works) have a .dll version as well which i need to move to another folder so the plugin will work. How can I solve this issue ?

**Comment by TheWaveWarden** [comment]
Hi @PietrareanuAndrei 
Developers starting to work after 2020 are no longer able to get a licence for VST2 (.dll) by Steinberg. Steinberg owns the VST technology, I cannot do anything about it. I am only allowed to distribute VST3.

That being said, Ableton 10.1 and higher does support VST3 and Odin 2 should show up. But as I see you already closed this issue :-)
