### ISSUE TITLE
[Bug Report] Some features unreachable on Retina MacBook Pro

### ISSUE THREAD

**Issue by PippoApps** [TheWaveWarden/odin2#444]
**Describe the bug**
VST on Reaper.
The GUI is not resizable, therefore the lower part is always off screen.
The lower controls are unreachable.

**To Reproduce**
1 - Open Reaper on a Retina MacbookPro with 1440x900 resolution.
2 - Open plugin GUI
3 - Set floating do everything you can to give maximum space available, and drag plugin window to the top
4 - Still, lower controls are not reachable

**Expected behavior**
The GUI to be either resizable or visible on Macbook Pros

**Screenshots**
Here's a full screenshot of my desktop.
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/29799572/202478327-a0d36af0-aecc-4534-9473-0e34c6ab380e.png">

**Desktop (please complete the following information):**
 - OS: MacOS catalina 10.15.7
 - DAW and version being used Reaper 5.983 and Reaper 6.70
 - Odin Version: latest downloaded today]
 - Plugin Format: VST3

**Additional context**

**Comment by TheWaveWarden** [comment]
Hi @PippoApps 

The UI is resizable from the top-right corner, as written in section 1.6 of the manual:

https://www.thewavewarden.com/assets/Odin2_manual_v2.3.0.pdf
