### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Canwisky** [TheWaveWarden/odin2#445]
**window size**

plug-in is too big, cant see the features below 😥

![image](https://user-images.githubusercontent.com/30913117/208332671-9b8a8ce1-e369-433b-94a6-0f240795156b.png)

**Comment by KottV** [comment]
press 100%

**Comment by TheWaveWarden** [comment]
Hi @Canwisky 
Yeah, as KottV said, you can rescale the UI in the top-right corner:

![Screenshot from 2022-12-19 13-12-43](https://user-images.githubusercontent.com/28705282/208423837-49115615-8c9e-43d0-b002-9c8844b12ba3.png)

**Comment by Canwisky** [comment]
thank you very much!
