### ISSUE TITLE
[Bug Report] Odin2 Compiling Fails

### ISSUE THREAD

**Issue by therealkitman** [TheWaveWarden/odin2#448]
**Describe the bug**
Odin2 fails to complete being compiled.

**To Reproduce**
1. Download source as per the Build Instructions -
2. git clone --recurse-submodules https://github.com/TheWaveWarden/odin2.git
3. cmake -B build -D CMAKE_BUILD_TYPE=Release 
4. cmake --build build --config Release then it fails to complete.

**Expected behavior**
A standalone and VST3 versions/

**Screenshots**
![image](https://user-images.githubusercontent.com/14888092/217697327-53edab75-f665-498f-9d07-cdcf72fddbc4.png)

**Desktop (please complete the following information):**
 - OS: Tumbleweed
 - Odin Version Master branch
 - Plugin Format [VST3 / AU / LV2]

**Additional context**
I tried to find the lv2.h manually but it's not in the odin2 folder structure.

**Comment by KottV** [comment]
you need `lv2-devel`

and here is the TW package alongside many other plugins https://build.opensuse.org/package/show/multimedia:proaudio/odin2

**Comment by therealkitman** [comment]
Ah, that fixed it!! I thought it odd as I had compiled LV2 from the surge project earlier.

Thanks very much :+1: 

PS. You might want to add that lv2-dev(el) package to the list of Linux Prerequisites.
